In [1]:
import pandas as pd
import numpy as np

In [2]:
batting_path = r"C:\stuff\DATA MINING PROJECT\data\processed\ipl\batting_match.csv"
bowling_path = r"C:\stuff\DATA MINING PROJECT\data\processed\ipl\bowling_match.csv"

batting = pd.read_csv(batting_path)
bowling = pd.read_csv(bowling_path)

print("Batting shape:", batting.shape)
print("Bowling shape:", bowling.shape)

Batting shape: (18768, 11)
Bowling shape: (14700, 13)

In [ ]:
recent_seasons = ["2022", "2023", "2024", "2025", "2026"]

batting = batting[
    batting["season"].astype(str).isin(recent_seasons)
].copy()

bowling = bowling[
    bowling["season"].astype(str).isin(recent_seasons)
].copy()

print("Batting shape:", batting.shape)
print("Bowling shape:", bowling.shape)

print("\nSeasons:")
print(sorted(batting["season"].unique()))

Batting shape: (5697, 11)
Bowling shape: (4334, 13)

Seasons:
['2022', '2023', '2024', '2025', '2026']

In [4]:
print("Batting records by season:")
display(
    batting.groupby("season")
    .size()
    .reset_index(name="records")
)

print("\nBowling records by season:")
display(
    bowling.groupby("season")
    .size()
    .reset_index(name="records")
)

Batting records by season:

  season  records
0   2022     1158
1   2023     1171
2   2024     1115
3   2025     1123
4   2026     1130

Bowling records by season:

  season  records
0   2022      857
1   2023      898
2   2024      857
3   2025      868
4   2026      854

In [5]:
batting_season = (
    batting
    .groupby(["player", "season"], as_index=False)
    .agg(
        batting_matches=("match_id", "nunique"),
        runs=("runs", "sum"),
        batting_balls=("balls", "sum"),
        fours=("fours", "sum"),
        sixes=("sixes", "sum")
    )
)

# Strike rate
batting_season["strike_rate"] = (
    batting_season["runs"] /
    batting_season["batting_balls"].replace(0, np.nan)
) * 100

# Boundary runs
batting_season["boundary_runs"] = (
    batting_season["fours"] * 4 +
    batting_season["sixes"] * 6
)

# Percentage of runs from boundaries
batting_season["boundary_percentage"] = (
    batting_season["boundary_runs"] /
    batting_season["runs"].replace(0, np.nan)
) * 100

print("Shape:", batting_season.shape)

display(batting_season.head(20))

Shape: (864, 10)

,player,season,batting_matches,runs,batting_balls,fours,sixes,strike_rate,boundary_runs,boundary_percentage
0,A Badoni,2022,11,161,130,11,7,123.846154,86,53.416149
1,A Badoni,2023,12,238,171,13,12,139.181287,124,52.100840
2,A Badoni,2024,12,235,171,22,5,137.426901,118,50.212766
3,A Badoni,2025,11,329,221,27,14,148.868778,192,58.358663
4,A Badoni,2026,10,215,141,23,9,152.482270,146,67.906977
5,A Kamboj,2024,1,2,2,0,0,100.000000,0,0.000000
6,A Kamboj,2025,5,14,12,2,0,116.666667,8,57.142857
7,A Kamboj,2026,4,58,36,3,4,161.111111,36,62.068966
8,A Manohar,2022,7,108,75,14,3,144.000000,74,68.518519
9,A Manohar,2023,6,114,83,6,7,137.349398,66,57.894737
10,A Manohar,2024,2,9,16,1,0,56.250000,4,44.444444
11,A Manohar,2025,5,61,61,2,4,100.000000,32,52.459016
12,A Mhatre,2025,7,240,127,31,11,188.976378,190,79.166667
13,A Mhatre,2026,6,201,112,20,12,179.464286,152,75.621891
14,A Mishra,2023,1,19,30,2,0,63.333333,8,42.105263
15,A Nortje,2022,1,1,6,0,0,16.666667,0,0.000000
16,A Nortje,2023,7,37,29,6,0,127.586207,24,64.864865
17,A Nortje,2024,2,4,8,0,0,50.000000,0,0.000000
18,A Nortje,2026,1,0,1,0,0,0.000000,0,NaN
19,A Raghuvanshi,2024,7,163,105,16,8,155.238095,112,68.711656

In [6]:
print("Unique batting players:", batting_season["player"].nunique())
print("Seasons:", batting_season["season"].nunique())

print("\nMissing values:")
display(batting_season.isna().sum())

Unique batting players: 343
Seasons: 5

Missing values:

player                  0
season                  0
batting_matches         0
runs                    0
batting_balls           0
fours                   0
sixes                   0
strike_rate             0
boundary_runs           0
boundary_percentage    44
dtype: int64

In [7]:
# ============================================
# BOWLING — PLAYER-SEASON FEATURES
# ============================================

bowling_season = (
    bowling
    .groupby(["player", "season"], as_index=False)
    .agg(
        bowling_matches=("match_id", "nunique"),
        bowling_balls=("balls", "sum"),
        runs_conceded=("runs_conceded", "sum"),
        wickets=("wickets", "sum")
    )
)

# Overs
bowling_season["overs"] = (
    bowling_season["bowling_balls"] / 6
)

# Economy
bowling_season["economy"] = (
    bowling_season["runs_conceded"] /
    bowling_season["overs"].replace(0, np.nan)
)

# Bowling strike rate
bowling_season["bowling_strike_rate"] = (
    bowling_season["bowling_balls"] /
    bowling_season["wickets"].replace(0, np.nan)
)

print("Shape:", bowling_season.shape)

display(bowling_season.head(20))

Shape: (653, 9)

,player,season,bowling_matches,bowling_balls,runs_conceded,wickets,overs,economy,bowling_strike_rate
0,A Badoni,2022,2,12,11,2,2.000000,5.500000,6.000000
1,A Badoni,2023,1,1,0,0,0.166667,0.000000,NaN
2,A Badoni,2024,2,12,25,0,2.000000,12.500000,NaN
3,A Badoni,2025,2,10,13,2,1.666667,7.800000,5.000000
4,A Badoni,2026,1,6,14,0,1.000000,14.000000,NaN
5,A Kamboj,2024,3,60,114,2,10.000000,11.400000,30.000000
6,A Kamboj,2025,8,129,172,8,21.500000,8.000000,16.125000
7,A Kamboj,2026,14,302,530,21,50.333333,10.529801,14.380952
8,A Mishra,2023,7,114,149,7,19.000000,7.842105,16.285714
9,A Mishra,2024,1,12,20,1,2.000000,10.000000,12.000000
10,A Nortje,2022,6,134,217,9,22.333333,9.716418,14.888889
11,A Nortje,2023,10,240,364,10,40.000000,9.100000,24.000000
12,A Nortje,2024,6,132,294,7,22.000000,13.363636,18.857143
13,A Nortje,2025,2,42,83,1,7.000000,11.857143,42.000000
14,A Nortje,2026,1,24,39,0,4.000000,9.750000,NaN
15,A Zampa,2023,6,132,188,8,22.000000,8.545455,16.500000
16,A Zampa,2025,2,48,94,2,8.000000,11.750000,24.000000
17,AD Russell,2022,13,169,278,17,28.166667,9.869822,9.941176
18,AD Russell,2023,9,91,172,7,15.166667,11.340659,13.000000
19,AD Russell,2024,14,176,295,19,29.333333,10.056818,9.263158

In [8]:
print("Unique bowling players:", bowling_season["player"].nunique())
print("Seasons:", bowling_season["season"].nunique())

print("\nMissing values:")
display(bowling_season.isna().sum())

Unique bowling players: 262
Seasons: 5

Missing values:

player                   0
season                   0
bowling_matches          0
bowling_balls            0
runs_conceded            0
wickets                  0
overs                    0
economy                  0
bowling_strike_rate    119
dtype: int64

In [9]:
# ============================================
# COMBINE BATTING + BOWLING
# ============================================

player_season = pd.merge(
    batting_season,
    bowling_season,
    on=["player", "season"],
    how="outer"
)

print("Player-season shape:", player_season.shape)
print("Unique players:", player_season["player"].nunique())
print("Seasons:", player_season["season"].nunique())

display(player_season.head(20))

Player-season shape: (1010, 17)
Unique players: 384
Seasons: 5

,player,season,batting_matches,runs,batting_balls,fours,sixes,strike_rate,boundary_runs,boundary_percentage,bowling_matches,bowling_balls,runs_conceded,wickets,overs,economy,bowling_strike_rate
0,A Badoni,2022,11.0,161.0,130.0,11.0,7.0,123.846154,86.0,53.416149,2.0,12.0,11.0,2.0,2.000000,5.500000,6.000000
1,A Badoni,2023,12.0,238.0,171.0,13.0,12.0,139.181287,124.0,52.100840,1.0,1.0,0.0,0.0,0.166667,0.000000,NaN
2,A Badoni,2024,12.0,235.0,171.0,22.0,5.0,137.426901,118.0,50.212766,2.0,12.0,25.0,0.0,2.000000,12.500000,NaN
3,A Badoni,2025,11.0,329.0,221.0,27.0,14.0,148.868778,192.0,58.358663,2.0,10.0,13.0,2.0,1.666667,7.800000,5.000000
4,A Badoni,2026,10.0,215.0,141.0,23.0,9.0,152.482270,146.0,67.906977,1.0,6.0,14.0,0.0,1.000000,14.000000,NaN
5,A Kamboj,2024,1.0,2.0,2.0,0.0,0.0,100.000000,0.0,0.000000,3.0,60.0,114.0,2.0,10.000000,11.400000,30.000000
6,A Kamboj,2025,5.0,14.0,12.0,2.0,0.0,116.666667,8.0,57.142857,8.0,129.0,172.0,8.0,21.500000,8.000000,16.125000
7,A Kamboj,2026,4.0,58.0,36.0,3.0,4.0,161.111111,36.0,62.068966,14.0,302.0,530.0,21.0,50.333333,10.529801,14.380952
8,A Manohar,2022,7.0,108.0,75.0,14.0,3.0,144.000000,74.0,68.518519,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,A Manohar,2023,6.0,114.0,83.0,6.0,7.0,137.349398,66.0,57.894737,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,A Manohar,2024,2.0,9.0,16.0,1.0,0.0,56.250000,4.0,44.444444,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,A Manohar,2025,5.0,61.0,61.0,2.0,4.0,100.000000,32.0,52.459016,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,A Mhatre,2025,7.0,240.0,127.0,31.0,11.0,188.976378,190.0,79.166667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,A Mhatre,2026,6.0,201.0,112.0,20.0,12.0,179.464286,152.0,75.621891,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,A Mishra,2023,1.0,19.0,30.0,2.0,0.0,63.333333,8.0,42.105263,7.0,114.0,149.0,7.0,19.000000,7.842105,16.285714
15,A Mishra,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,12.0,20.0,1.0,2.000000,10.000000,12.000000
16,A Nortje,2022,1.0,1.0,6.0,0.0,0.0,16.666667,0.0,0.000000,6.0,134.0,217.0,9.0,22.333333,9.716418,14.888889
17,A Nortje,2023,7.0,37.0,29.0,6.0,0.0,127.586207,24.0,64.864865,10.0,240.0,364.0,10.0,40.000000,9.100000,24.000000
18,A Nortje,2024,2.0,4.0,8.0,0.0,0.0,50.000000,0.0,0.000000,6.0,132.0,294.0,7.0,22.000000,13.363636,18.857143
19,A Nortje,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,42.0,83.0,1.0,7.000000,11.857143,42.000000

In [10]:
count_columns = [
    "batting_matches",
    "runs",
    "batting_balls",
    "fours",
    "sixes",
    "boundary_runs",
    "bowling_matches",
    "bowling_balls",
    "runs_conceded",
    "wickets",
    "overs"
]

for col in count_columns:
    player_season[col] = player_season[col].fillna(0)

In [11]:
print("Final player-season shape:", player_season.shape)

print(
    "Unique players:",
    player_season["player"].nunique()
)

print(
    "Seasons:",
    sorted(player_season["season"].unique())
)

display(
    player_season
    .sort_values(["player", "season"])
    .head(30)
)

Final player-season shape: (1010, 17)
Unique players: 384
Seasons: ['2022', '2023', '2024', '2025', '2026']

,player,season,batting_matches,runs,batting_balls,fours,sixes,strike_rate,boundary_runs,boundary_percentage,bowling_matches,bowling_balls,runs_conceded,wickets,overs,economy,bowling_strike_rate
0,A Badoni,2022,11.0,161.0,130.0,11.0,7.0,123.846154,86.0,53.416149,2.0,12.0,11.0,2.0,2.000000,5.500000,6.000000
1,A Badoni,2023,12.0,238.0,171.0,13.0,12.0,139.181287,124.0,52.100840,1.0,1.0,0.0,0.0,0.166667,0.000000,NaN
2,A Badoni,2024,12.0,235.0,171.0,22.0,5.0,137.426901,118.0,50.212766,2.0,12.0,25.0,0.0,2.000000,12.500000,NaN
3,A Badoni,2025,11.0,329.0,221.0,27.0,14.0,148.868778,192.0,58.358663,2.0,10.0,13.0,2.0,1.666667,7.800000,5.000000
4,A Badoni,2026,10.0,215.0,141.0,23.0,9.0,152.482270,146.0,67.906977,1.0,6.0,14.0,0.0,1.000000,14.000000,NaN
5,A Kamboj,2024,1.0,2.0,2.0,0.0,0.0,100.000000,0.0,0.000000,3.0,60.0,114.0,2.0,10.000000,11.400000,30.000000
6,A Kamboj,2025,5.0,14.0,12.0,2.0,0.0,116.666667,8.0,57.142857,8.0,129.0,172.0,8.0,21.500000,8.000000,16.125000
7,A Kamboj,2026,4.0,58.0,36.0,3.0,4.0,161.111111,36.0,62.068966,14.0,302.0,530.0,21.0,50.333333,10.529801,14.380952
8,A Manohar,2022,7.0,108.0,75.0,14.0,3.0,144.000000,74.0,68.518519,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
9,A Manohar,2023,6.0,114.0,83.0,6.0,7.0,137.349398,66.0,57.894737,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
10,A Manohar,2024,2.0,9.0,16.0,1.0,0.0,56.250000,4.0,44.444444,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
11,A Manohar,2025,5.0,61.0,61.0,2.0,4.0,100.000000,32.0,52.459016,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
12,A Mhatre,2025,7.0,240.0,127.0,31.0,11.0,188.976378,190.0,79.166667,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
13,A Mhatre,2026,6.0,201.0,112.0,20.0,12.0,179.464286,152.0,75.621891,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
14,A Mishra,2023,1.0,19.0,30.0,2.0,0.0,63.333333,8.0,42.105263,7.0,114.0,149.0,7.0,19.000000,7.842105,16.285714
15,A Mishra,2024,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,1.0,12.0,20.0,1.0,2.000000,10.000000,12.000000
16,A Nortje,2022,1.0,1.0,6.0,0.0,0.0,16.666667,0.0,0.000000,6.0,134.0,217.0,9.0,22.333333,9.716418,14.888889
17,A Nortje,2023,7.0,37.0,29.0,6.0,0.0,127.586207,24.0,64.864865,10.0,240.0,364.0,10.0,40.000000,9.100000,24.000000
18,A Nortje,2024,2.0,4.0,8.0,0.0,0.0,50.000000,0.0,0.000000,6.0,132.0,294.0,7.0,22.000000,13.363636,18.857143
19,A Nortje,2025,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,2.0,42.0,83.0,1.0,7.000000,11.857143,42.000000
20,A Nortje,2026,1.0,0.0,1.0,0.0,0.0,0.000000,0.0,NaN,1.0,24.0,39.0,0.0,4.000000,9.750000,NaN
21,A Raghuvanshi,2024,7.0,163.0,105.0,16.0,8.0,155.238095,112.0,68.711656,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
22,A Raghuvanshi,2025,11.0,300.0,214.0,30.0,8.0,140.186916,168.0,56.000000,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
23,A Raghuvanshi,2026,12.0,422.0,287.0,40.0,19.0,147.038328,274.0,64.928910,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
24,A Tomar,2022,1.0,4.0,8.0,1.0,0.0,50.000000,4.0,100.000000,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
25,A Zampa,2023,3.0,10.0,16.0,0.0,0.0,62.500000,0.0,0.000000,6.0,132.0,188.0,8.0,22.000000,8.545455,16.500000
26,A Zampa,2025,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,2.0,48.0,94.0,2.0,8.000000,11.750000,24.000000
27,AA Kulkarni,2024,2.0,9.0,8.0,2.0,0.0,112.500000,8.0,88.888889,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
28,AA Kulkarni,2026,2.0,17.0,25.0,1.0,0.0,68.000000,4.0,23.529412,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
29,AD Russell,2022,12.0,335.0,189.0,18.0,32.0,177.248677,264.0,78.805970,13.0,169.0,278.0,17.0,28.166667,9.869822,9.941176

In [12]:
# ============================================
# SAVE PLAYER-SEASON FEATURES
# ============================================

output_path = r"C:\stuff\DATA MINING PROJECT\data\processed\ipl\player_season_features.csv"

player_season.to_csv(
    output_path,
    index=False
)

print("Saved successfully!")
print(output_path)

Saved successfully!
C:\stuff\DATA MINING PROJECT\data\processed\ipl\player_season_features.csv