In [2]:
import pyreadr

file_path = r"C:\stuff\DATA MINING PROJECT\data\raw\cricketdata_0.3.0\cricketdata\data\player_meta.rda"

result = pyreadr.read_r(file_path)

print(result.keys())

odict_keys(['player_meta'])

c:\Users\legen\anaconda3\Lib\site-packages\pyreadr\_pyreadr_parser.py:233: RuntimeWarning: invalid value encountered in cast
  df[colname] = df[colname].values.astype("datetime64[D]").astype(datetime)

In [3]:
player_meta = result["player_meta"]

print("Shape:", player_meta.shape)
print("\nColumns:")
print(player_meta.columns.tolist())

display(player_meta.head(10))

Shape: (16101, 11)

Columns:
['cricinfo_id', 'cricsheet_id', 'unique_name', 'full_name', 'name', 'country', 'dob', 'batting_style', 'bowling_style', 'birthplace', 'playing_role']

,cricinfo_id,cricsheet_id,unique_name,full_name,name,country,dob,batting_style,bowling_style,birthplace,playing_role
0,1437344,e2c882d1,AN Lascu,Adrian Nicholas Lascu,Adrian Nicholas Lascu,Romania,1998-12-17,Right-hand bat,Right-arm medium,NaN,NaN
1,1321753,4c7d4170,A Le Ray,Annie Le Ray,Annie Le Ray,Guernsey,None,NaN,NaN,NaN,NaN
2,1409303,2327fdc7,AA Rahayu,Apriliandi Abdillah Rahayu,Apriliandi Rahayu,Indonesia,2000-04-24,Right-hand bat,Right-arm medium,NaN,NaN
3,1438325,a35e3f07,A Joshi,Avaniben Joshi,Avaniben Joshi,Czech Republic,1983-04-15,Right-hand bat,Right-arm medium,NaN,NaN
4,1429988,6a32ef43,CT McNally,Christine Tracey McNally,Christine McNally,Gibraltar,1981-04-16,Right-hand bat,Right-arm medium,NaN,NaN
5,1451259,c73c75f9,FFJ Heo,Febrianto Frans Jordi Heo,Febrianto Heo,Indonesia,1997-02-06,Right-hand bat,Right-arm offbreak,NaN,NaN
6,1438800,98e3f1de,S Burdekin,Scott Burdekin,Scott Burdekin,Cyprus,1995-03-01,Right-hand bat,Right-arm offbreak,NaN,NaN
7,1429993,3aac5463,YS Blagg,Yanira Sebastian Blagg,Yanira Blagg,Gibraltar,2006-02-18,Right-hand bat,Right-arm medium,NaN,NaN
8,1326690,ef3aeb35,L Thobela,-Lihle Thobela,Lihle Thobela,Eswatini,2000-04-29,Right-hand bat,Right-arm medium,NaN,NaN
9,1175501,21d38d47,A Aravinddaraj,A Aravinddaraj,NaN,India,1996-06-09,Right hand Bat,Right arm Medium,NaN,NaN

In [4]:
player_meta.info()

<class 'pandas.DataFrame'>
RangeIndex: 16101 entries, 0 to 16100
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cricinfo_id    16101 non-null  str
 1   cricsheet_id   16101 non-null  str
 2   unique_name    16099 non-null  str
 3   full_name      16070 non-null  str
 4   name           2025 non-null   str
 5   country        16101 non-null  str
 6   dob            15258 non-null  object
 7   batting_style  14397 non-null  str
 8   bowling_style  12000 non-null  str
 9   birthplace     9938 non-null   str
 10  playing_role   4836 non-null   str
dtypes: object(1), str(10)
memory usage: 2.8+ MB

In [5]:
import os

output_path = r"C:\stuff\DATA MINING PROJECT\data\raw\player_metadata.csv"

player_meta.to_csv(output_path, index=False)

print("Saved successfully!")
print(output_path)
print("Rows:", len(player_meta))
print("Columns:", len(player_meta.columns))

Saved successfully!
C:\stuff\DATA MINING PROJECT\data\raw\player_metadata.csv
Rows: 16101
Columns: 11

In [6]:
import os
import pandas as pd

project_path = r"C:\stuff\DATA MINING PROJECT"

# Find all CSV files in the project
csv_files = []

for root, dirs, files in os.walk(project_path):
    for file in files:
        if file.lower().endswith(".csv"):
            csv_files.append(os.path.join(root, file))

print("CSV files found:", len(csv_files))

for f in csv_files:
    print(f)

CSV files found: 23
C:\stuff\DATA MINING PROJECT\data\processed\bbl\batting_match.csv
C:\stuff\DATA MINING PROJECT\data\processed\bbl\bowling_match.csv
C:\stuff\DATA MINING PROJECT\data\processed\bbl\matches.csv
C:\stuff\DATA MINING PROJECT\data\processed\ipl\batting_match.csv
C:\stuff\DATA MINING PROJECT\data\processed\ipl\bowling_match.csv
C:\stuff\DATA MINING PROJECT\data\processed\ipl\matches.csv
C:\stuff\DATA MINING PROJECT\data\processed\ipl\player_master.csv
C:\stuff\DATA MINING PROJECT\data\processed\odi\batting_match.csv
C:\stuff\DATA MINING PROJECT\data\processed\odi\bowling_match.csv
C:\stuff\DATA MINING PROJECT\data\processed\odi\matches.csv
C:\stuff\DATA MINING PROJECT\data\processed\smat\batting_match.csv
C:\stuff\DATA MINING PROJECT\data\processed\smat\bowling_match.csv
C:\stuff\DATA MINING PROJECT\data\processed\smat\matches.csv
C:\stuff\DATA MINING PROJECT\data\processed\t20\batting_match.csv
C:\stuff\DATA MINING PROJECT\data\processed\t20\bowling_match.csv
C:\stuff\DATA MINING PROJECT\data\processed\t20\matches.csv
C:\stuff\DATA MINING PROJECT\data\processed\t20_wc\batting_match.csv
C:\stuff\DATA MINING PROJECT\data\processed\t20_wc\bowling_match.csv
C:\stuff\DATA MINING PROJECT\data\processed\t20_wc\matches.csv
C:\stuff\DATA MINING PROJECT\data\raw\bat.csv
C:\stuff\DATA MINING PROJECT\data\raw\bowl.csv
C:\stuff\DATA MINING PROJECT\data\raw\people.csv
C:\stuff\DATA MINING PROJECT\data\raw\player_metadata.csv

In [7]:
import pandas as pd

base = r"C:\stuff\DATA MINING PROJECT\data\processed\ipl"

batting = pd.read_csv(base + r"\batting_match.csv")
bowling = pd.read_csv(base + r"\bowling_match.csv")

print("========== BATTING ==========")
print("Shape:", batting.shape)
print("Columns:")
print(batting.columns.tolist())

print("\n========== BOWLING ==========")
print("Shape:", bowling.shape)
print("Columns:")
print(bowling.columns.tolist())

print("\n========== BATTING SAMPLE ==========")
display(batting.head())

print("\n========== BOWLING SAMPLE ==========")
display(bowling.head())

========== BATTING ==========
Shape: (18768, 11)
Columns:
['match_id', 'competition', 'season', 'date', 'team', 'player', 'runs', 'balls', 'fours', 'sixes', 'strike_rate']

========== BOWLING ==========
Shape: (14700, 13)
Columns:
['match_id', 'competition', 'season', 'date', 'bowling_team', 'opposition', 'player', 'balls', 'runs_conceded', 'wickets', 'overs', 'economy', 'bowling_strike_rate']

========== BATTING SAMPLE ==========

,match_id,competition,season,date,team,player,runs,balls,fours,sixes,strike_rate
0,1082591,IPL,2017,2017-04-05,Royal Challengers Bangalore,A Choudhary,6,2,0,1,300.00
1,1082591,IPL,2017,2017-04-05,Royal Challengers Bangalore,CH Gayle,32,21,2,3,152.38
2,1082591,IPL,2017,2017-04-05,Royal Challengers Bangalore,KM Jadhav,31,15,4,1,206.67
3,1082591,IPL,2017,2017-04-05,Royal Challengers Bangalore,Mandeep Singh,24,16,5,0,150.00
4,1082591,IPL,2017,2017-04-05,Royal Challengers Bangalore,S Aravind,0,2,0,0,0.00

========== BOWLING SAMPLE ==========

,match_id,competition,season,date,bowling_team,opposition,player,balls,runs_conceded,wickets,overs,economy,bowling_strike_rate
0,1082591,IPL,2017,2017-04-05,Royal Challengers Bangalore,Sunrisers Hyderabad,A Choudhary,24,55,1,4.0,13.75,24.0
1,1082591,IPL,2017,2017-04-05,Royal Challengers Bangalore,Sunrisers Hyderabad,S Aravind,18,36,0,3.0,12.00,NaN
2,1082591,IPL,2017,2017-04-05,Royal Challengers Bangalore,Sunrisers Hyderabad,SR Watson,18,41,0,3.0,13.67,NaN
3,1082591,IPL,2017,2017-04-05,Royal Challengers Bangalore,Sunrisers Hyderabad,STR Binny,6,10,1,1.0,10.00,6.0
4,1082591,IPL,2017,2017-04-05,Royal Challengers Bangalore,Sunrisers Hyderabad,TM Head,6,11,0,1.0,11.00,NaN

In [8]:
people_path = r"C:\stuff\DATA MINING PROJECT\data\raw\people.csv"

people = pd.read_csv(people_path)

print("Shape:", people.shape)
print("\nColumns:")
print(people.columns.tolist())

display(people.head(10))

people.info()

Shape: (18507, 22)

Columns:
['identifier', 'name', 'unique_name', 'key_bcci', 'key_bcci_2', 'key_bigbash', 'key_cricbuzz', 'key_cricheroes', 'key_crichq', 'key_cricinfo', 'key_cricinfo_2', 'key_cricinfo_3', 'key_cricingif', 'key_cricketarchive', 'key_cricketarchive_2', 'key_cricketworld', 'key_nvplay', 'key_nvplay_2', 'key_opta', 'key_opta_2', 'key_pulse', 'key_pulse_2']

,identifier,name,unique_name,key_bcci,key_bcci_2,key_bigbash,key_cricbuzz,key_cricheroes,key_crichq,key_cricinfo,...,key_cricingif,key_cricketarchive,key_cricketarchive_2,key_cricketworld,key_nvplay,key_nvplay_2,key_opta,key_opta_2,key_pulse,key_pulse_2
0,b4a23876,AAA Amsterdam,AAA Amsterdam,NaN,NaN,NaN,NaN,NaN,NaN,772407.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,482762af,AA Adeoye,AA Adeoye,NaN,NaN,NaN,NaN,NaN,NaN,380588.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4b0e3049,AA Alleyne,AA Alleyne,NaN,NaN,NaN,NaN,NaN,NaN,661441.0,...,NaN,1512811.0,NaN,NaN,NaN,NaN,NaN,NaN,18542.0,NaN
3,fd3c5c00,AAA Patel,AAA Patel,NaN,NaN,NaN,NaN,NaN,NaN,1163136.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bc005f0d,AAA White,AAA White,NaN,NaN,NaN,NaN,NaN,NaN,474307.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5c67c7a6,AA Baig,AA Baig,NaN,NaN,NaN,NaN,NaN,NaN,524897.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,95d3f620,AA Balogun,AA Balogun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,6a58e069,AA Bamal,AA Bamal,i0X1KhUIJLIzQOiJAiebGCiVyJJeiOc,NaN,NaN,NaN,NaN,NaN,1123075.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,02d11602,AA Banner,AA Banner,NaN,NaN,NaN,NaN,NaN,NaN,590021.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,b690f34a,AA Barot,AA Barot,KVGiiAJbJeyiJCIeiXLzJ1OcO0UihIQ,NaN,NaN,NaN,NaN,NaN,398519.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.DataFrame'>
RangeIndex: 18507 entries, 0 to 18506
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   identifier            18507 non-null  str
 1   name                  18507 non-null  str
 2   unique_name           18507 non-null  str
 3   key_bcci              1321 non-null   str
 4   key_bcci_2            8 non-null      str
 5   key_bigbash           296 non-null    float64
 6   key_cricbuzz          50 non-null     float64
 7   key_cricheroes        111 non-null    float64
 8   key_crichq            24 non-null     float64
 9   key_cricinfo          18462 non-null  float64
 10  key_cricinfo_2        102 non-null    float64
 11  key_cricinfo_3        1 non-null      float64
 12  key_cricingif         130 non-null    float64
 13  key_cricketarchive    4508 non-null   float64
 14  key_cricketarchive_2  1 non-null      float64
 15  key_cricketworld      127 non-null    float64
 16  key_nvplay            1135 non-null   str
 17  key_nvplay_2          34 non-null     str
 18  key_opta              67 non-null     float64
 19  key_opta_2            1 non-null      float64
 20  key_pulse             2010 non-null   float64
 21  key_pulse_2           13 non-null     float64
dtypes: float64(15), str(7)
memory usage: 3.7 MB

In [9]:
# Check how many player IDs overlap between people.csv and player metadata

people_ids = set(people["identifier"].dropna().astype(str))
metadata_ids = set(player_meta["cricsheet_id"].dropna().astype(str))

overlap = people_ids & metadata_ids

print("People IDs:", len(people_ids))
print("Metadata IDs:", len(metadata_ids))
print("Matching IDs:", len(overlap))

print(
    "Match percentage:",
    round(len(overlap) / len(metadata_ids) * 100, 2),
    "%"
)

People IDs: 18507
Metadata IDs: 16093
Matching IDs: 16074
Match percentage: 99.88 %

In [10]:
ipl_players = set(batting["player"].dropna().astype(str))

print("Unique IPL batting players:", len(ipl_players))

display(
    batting[["player"]]
    .drop_duplicates()
    .head(30)
)

Unique IPL batting players: 738

           player
0     A Choudhary
1        CH Gayle
2       KM Jadhav
3   Mandeep Singh
4       S Aravind
5       SR Watson
6       STR Binny
7     Sachin Baby
8         TM Head
9        TS Mills
10      YS Chahal
11    BCJ Cutting
12      DA Warner
13       DJ Hooda
14   MC Henriques
15       S Dhawan
16   Yuvraj Singh
17      AT Rayudu
18      HH Pandya
19     JC Buttler
20     KA Pollard
21      KH Pandya
22         N Rana
23       PA Patel
24      RG Sharma
25     TG Southee
26      AM Rahane
27      BA Stokes
28     MA Agarwal
29       MS Dhoni

In [11]:
people[["identifier", "name", "unique_name"]].head(20)

   identifier            name     unique_name
0    b4a23876   AAA Amsterdam   AAA Amsterdam
1    482762af       AA Adeoye       AA Adeoye
2    4b0e3049      AA Alleyne      AA Alleyne
3    fd3c5c00       AAA Patel       AAA Patel
4    bc005f0d       AAA White       AAA White
5    5c67c7a6         AA Baig         AA Baig
6    95d3f620      AA Balogun      AA Balogun
7    6a58e069        AA Bamal        AA Bamal
8    02d11602       AA Banner       AA Banner
9    b690f34a        AA Barot        AA Barot
10   c7a9ffbf    AA Bevilaqua    AA Bevilaqua
11   bff458c6     AA Bilakhia     AA Bilakhia
12   44e58b5b  AA Chakraborty  AA Chakraborty
13   29d72eb2       AA Chavan       AA Chavan
14   b2c38dce    AA Choudhury    AA Choudhury
15   d37fd2c3         A Adams         A Adams
16   fdcc7fe6       AA Darlow       AA Darlow
17   1b0ce76e      A Adekunle      A Adekunle
18   cfa56623    AA Deshpande    AA Deshpande
19   b8f6fb20       A Adetoro       A Adetoro

In [12]:
import pandas as pd

# Load player metadata
metadata_path = r"C:\stuff\DATA MINING PROJECT\data\raw\player_metadata.csv"
player_meta = pd.read_csv(metadata_path)

# people.csv
people_path = r"C:\stuff\DATA MINING PROJECT\data\raw\people.csv"
people = pd.read_csv(people_path)

# IPL batting data
batting_path = r"C:\stuff\DATA MINING PROJECT\data\processed\ipl\batting_match.csv"
batting = pd.read_csv(batting_path)

print("Player metadata:", player_meta.shape)
print("People:", people.shape)
print("IPL batting:", batting.shape)

Player metadata: (16101, 11)
People: (18507, 22)
IPL batting: (18768, 11)

In [13]:
people_ids = set(
    people["identifier"]
    .dropna()
    .astype(str)
)

metadata_ids = set(
    player_meta["cricsheet_id"]
    .dropna()
    .astype(str)
)

overlap = people_ids & metadata_ids

print("People IDs:", len(people_ids))
print("Metadata IDs:", len(metadata_ids))
print("Matching IDs:", len(overlap))

print(
    "Match percentage:",
    round(len(overlap) / len(metadata_ids) * 100, 2),
    "%"
)

People IDs: 18507
Metadata IDs: 16093
Matching IDs: 16074
Match percentage: 99.88 %

In [14]:
ipl_players = (
    batting["player"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

print("Unique IPL players:", len(ipl_players))

# Check exact matches against people.name
exact_name_matches = set(ipl_players) & set(people["name"].astype(str))

print("Exact matches with people.name:", len(exact_name_matches))
print(
    "Exact match percentage:",
    round(len(exact_name_matches) / len(ipl_players) * 100, 2),
    "%"
)

Unique IPL players: 738
Exact matches with people.name: 736
Exact match percentage: 99.73 %

In [15]:
display(
    people[
        people["name"].isin(ipl_players)
    ][
        ["identifier", "name", "unique_name", "key_cricinfo"]
    ].head(30)
)

    identifier             name      unique_name  key_cricinfo
11    bff458c6      AA Bilakhia      AA Bilakhia       26946.0
13    29d72eb2        AA Chavan        AA Chavan      337913.0
37    2815fe50  AA Jhunjhunwala  AA Jhunjhunwala       29702.0
47    2d140b79      AA Kulkarni      AA Kulkarni     1403153.0
79    b69e69ed        AA Noffke        AA Noffke        6938.0
110   1c2a64cd   A Ashish Reddy   A Ashish Reddy      389605.0
128   872b03f7         A Badoni         A Badoni     1151270.0
130   fa463154       AB Agarkar       AB Agarkar       26184.0
136   d3a3e82d        AB Barath        AB Barath      274926.0
145   c4487b84   AB de Villiers   AB de Villiers       44936.0
146   66b30f71         AB Dinda         AB Dinda      227712.0
150   cc777ffa     Abdul Basith     Abdul Basith     1287067.0
210   8e514b4c      Abdul Samad      Abdul Samad     1175485.0
211   21dbacff      Abdul Samad  Abdul Samad (2)     1431566.0
212   8e554b6b      Abdul Samad  Abdul Samad (3)     1073106.0
225   888e32bf     Abdur Razzak     Abdur Razzak       56283.0
271   f29185a1  Abhishek Sharma  Abhishek Sharma     1070183.0
287   ad3b6e95    Abishek Porel    Abishek Porel     1277545.0
296   16043342      AB McDonald      AB McDonald        6553.0
340   1efb8a28      AC Blizzard      AC Blizzard        4498.0
356   2b6e6dec     AC Gilchrist     AC Gilchrist        5390.0
358   99b202b3       A Chandila       A Chandila       27783.0
371   e249fdaa         A Chopra         A Chopra       27639.0
372   57a7b064         A Chopra     Anjum Chopra       53910.0
373   18e6906e      A Choudhary      A Choudhary      527299.0
412   b552a935        AC Thomas        AC Thomas       47569.0
415   864c199e         AC Voges         AC Voges        8119.0
427   5b16a806      A Dananjaya      A Dananjaya      574178.0
463   92aeac25         AD Hales         AD Hales      249866.0
499   3edb58fc   AD Mascarenhas   AD Mascarenhas       16932.0

In [16]:
# Find IPL players that don't have an exact match in people.name

people_names = set(
    people["name"]
    .dropna()
    .astype(str)
    .str.strip()
)

unmatched_players = sorted(
    set(ipl_players) - people_names
)

print("Unmatched IPL players:", len(unmatched_players))
print(unmatched_players)

people_unique_names = set(
    people["unique_name"]
    .dropna()
    .astype(str)
    .str.strip()
)

unique_name_matches = set(unmatched_players) & people_unique_names

print("Matches in unique_name:", len(unique_name_matches))
print(unique_name_matches)

Unmatched IPL players: 2
['Arshad Khan (2)', 'Salil Arora']
Matches in unique_name: 2
{'Arshad Khan (2)', 'Salil Arora'}

In [17]:
# Create a clean lookup from player name → Cricsheet ID

people_lookup = people[
    ["identifier", "name", "unique_name"]
].copy()

# First try the normal name
name_to_id = dict(
    zip(
        people_lookup["name"].astype(str).str.strip(),
        people_lookup["identifier"].astype(str).str.strip()
    )
)

# Add unique_name as fallback
unique_name_to_id = dict(
    zip(
        people_lookup["unique_name"].astype(str).str.strip(),
        people_lookup["identifier"].astype(str).str.strip()
    )
)

# Map IPL player names to Cricsheet IDs
ipl_player_mapping = []

for player in sorted(ipl_players):
    if player in name_to_id:
        cricsheet_id = name_to_id[player]
        match_type = "name"
    elif player in unique_name_to_id:
        cricsheet_id = unique_name_to_id[player]
        match_type = "unique_name"
    else:
        cricsheet_id = None
        match_type = "unmatched"

    ipl_player_mapping.append({
        "player": player,
        "cricsheet_id": cricsheet_id,
        "match_type": match_type
    })

ipl_player_mapping = pd.DataFrame(ipl_player_mapping)

display(ipl_player_mapping.head(20))

            player cricsheet_id match_type
0   A Ashish Reddy     1c2a64cd       name
1         A Badoni     872b03f7       name
2       A Chandila     99b202b3       name
3         A Chopra     57a7b064       name
4      A Choudhary     18e6906e       name
5      A Dananjaya     5b16a806       name
6       A Flintoff     ddc0828d       name
7         A Kamboj     fcc21ace       name
8         A Kumble     0c2730df       name
9        A Manohar     0890552f       name
10        A Mhatre     b2b4f545       name
11        A Mishra     54690147       name
12        A Mithun     66cf56a5       name
13        A Mukund     6165bca6       name
14         A Nehra     96fd40ae       name
15        A Nortje     acdc62f5       name
16   A Raghuvanshi     d7017798       name
17         A Singh     5b040b81       name
18       A Symonds     bd77eb62       name
19         A Tomar     aa5d8c9e       name

In [18]:
print(
    ipl_player_mapping["match_type"].value_counts()
)

match_type
name           736
unique_name      2
Name: count, dtype: int64

In [19]:
# Keep only the metadata fields we actually need
metadata_columns = [
    "cricsheet_id",
    "cricinfo_id",
    "unique_name",
    "full_name",
    "name",
    "country",
    "dob",
    "batting_style",
    "bowling_style",
    "birthplace",
    "playing_role"
]

metadata_clean = player_meta[metadata_columns].copy()

# Make sure the join keys have the same type
ipl_player_mapping["cricsheet_id"] = (
    ipl_player_mapping["cricsheet_id"]
    .astype(str)
    .str.strip()
)

metadata_clean["cricsheet_id"] = (
    metadata_clean["cricsheet_id"]
    .astype(str)
    .str.strip()
)

# Merge IPL players with metadata
player_master = ipl_player_mapping.merge(
    metadata_clean,
    on="cricsheet_id",
    how="left",
    validate="one_to_one"
)

print("Player master shape:", player_master.shape)

display(player_master.head(20))

MergeError: Merge keys are not unique in either left or right dataset; not a one-to-one merge.
Duplicates in left:
 cricsheet_id
    12314277 ...
Duplicates in right:
 cricsheet_id
    4f91427c
    26a8b2fe
    e3273ac2
    2cc557f8
    cf785dd1 ...

In [ ]:
# Check duplicate Cricsheet IDs in player metadata

duplicates = (
    metadata_clean[
        metadata_clean["cricsheet_id"].duplicated(keep=False)
    ]
    .sort_values("cricsheet_id")
)

print("Duplicate cricsheet IDs:", duplicates["cricsheet_id"].nunique())
print("Rows involved:", len(duplicates))

display(duplicates.head(30))
print(
    "Duplicate IDs in IPL mapping:",
    ipl_player_mapping["cricsheet_id"].duplicated().sum()
)

Duplicate cricsheet IDs: 8
Rows involved: 16

,cricsheet_id,cricinfo_id,unique_name,full_name,name,country,dob,batting_style,bowling_style,birthplace,playing_role
13098,16301313,271884,S Wetoto,Sarah Wetoto,Sarah Wetoto,Kenya,1988-08-29,Right-hand bat,Right-arm offbreak,NaN,NaN
13099,16301313,1119429,S Wetoto,Sarah Wetoto,NaN,Kenya,1988-08-29,Right hand Bat,Right arm Offbreak,NaN,NaN
5384,26a8b2fe,1398125,Hassan Nawaz,Hasan Nawaz,Hasan Nawaz,Pakistan,2002-08-21,Right-hand bat,Right-arm medium,NaN,NaN
5407,26a8b2fe,1329695,Hassan Nawaz,Hassan Nawaz,NaN,Pakistan,NaN,Right hand Bat,Right arm Offbreak,NaN,NaN
5855,2cc557f8,917073,Imran Khan (3),Imran Khan,NaN,Fiji,NaN,NaN,NaN,NaN,NaN
9602,2cc557f8,519029,Imran Khan (3),Mohammad Imran Khan,Mohammad Khan,Fiji,1984-05-23,Left-hand bat,Left-arm medium,NaN,NaN
12032,37525dbf,973795,R Altaff Hussein,Riaz Altaff Hussein,NaN,Singapore,NaN,NaN,NaN,NaN,NaN
12033,37525dbf,422584,R Altaff Hussein,Riaz Altaff Hussien,Riaz Hussien,Singapore,1983-09-18,Right-hand bat,Right-arm offbreak,NaN,NaN
2486,4f91427c,647743,Cakacaka Cokovaki,Cakacaka Tikoisuva,Cakacaka Tikoisuva,Fiji,1997-05-31,Right-hand bat,Right-arm medium,NaN,NaN
2487,4f91427c,1082730,Cakacaka Cokovaki,Cakacaka Tikoisuva Cokovaki,NaN,Fiji,1997-09-12,NaN,Right arm Medium fast,NaN,NaN
1534,cf785dd1,520121,M Armghan Khan,Armaghan Khan,Armaghan Khan,Spain,1980-11-22,NaN,NaN,NaN,NaN
9928,cf785dd1,1046639,M Armghan Khan,Muhammad Armghan Khan,NaN,Spain,1980-11-22,NaN,NaN,NaN,NaN
14558,e0bed605,454834,T Tshering,Tashi Tshering,NaN,Bhutan,1990-01-16,Right hand Bat,NaN,"Yongtse, Bhutan",NaN
14559,e0bed605,552759,T Tshering,Tashi Yoedzer Tshering,Tashi Tshering,Bhutan,1990-01-16,Right-hand bat,NaN,NaN,NaN
8717,e3273ac2,517481,Mansoor Qureshi,Mansoor Ahmed Qureshi,Mansoor Qureshi,England,1965-08-31,NaN,NaN,NaN,NaN
8722,e3273ac2,1096129,Mansoor Qureshi,Mansoor Qureshi,NaN,England,NaN,NaN,NaN,NaN,NaN

Duplicate IDs in IPL mapping: 1

In [ ]:
duplicate_ipl = ipl_player_mapping[
    ipl_player_mapping["cricsheet_id"].duplicated(keep=False)
].sort_values("cricsheet_id")

display(duplicate_ipl)

             player cricsheet_id   match_type
86      Arshad Khan     12314277         name
87  Arshad Khan (2)     12314277  unique_name

In [ ]:
duplicate_metadata_ids = set(
    duplicates["cricsheet_id"]
)

ipl_duplicate_metadata = player_master_ids = ipl_player_mapping[
    ipl_player_mapping["cricsheet_id"].isin(duplicate_metadata_ids)
].sort_values("cricsheet_id")

display(ipl_duplicate_metadata)

Empty DataFrame
Columns: [player, cricsheet_id, match_type]
Index: []

In [ ]:
duplicate_id = duplicate_ipl["cricsheet_id"].iloc[0]

print("Duplicate Cricsheet ID:", duplicate_id)

display(
    player_meta[
        player_meta["cricsheet_id"].astype(str).str.strip() == duplicate_id
    ]
)

Duplicate Cricsheet ID: 12314277

,cricinfo_id,cricsheet_id,unique_name,full_name,name,country,dob,batting_style,bowling_style,birthplace,playing_role
9789,1244751,12314277,Arshad Khan (2),Mohd Arshad Khan,NaN,India,1997-12-20,Left hand Bat,Left arm Medium,Gopalganj (Seoni),Bowler

In [ ]:
# Create one metadata record per Cricsheet ID
metadata_unique = (
    metadata_clean
    .drop_duplicates(subset="cricsheet_id", keep="first")
    .copy()
)

print("Metadata rows before:", len(metadata_clean))
print("Metadata rows after:", len(metadata_unique))

# Create one player master record per Cricsheet ID
player_master = (
    ipl_player_mapping
    .dropna(subset=["cricsheet_id"])
    .drop_duplicates(subset=["cricsheet_id"], keep="first")
    .merge(
        metadata_unique,
        on="cricsheet_id",
        how="left",
        validate="one_to_one"
    )
)

print("Player master shape:", player_master.shape)

display(player_master.head(20))

Metadata rows before: 16101
Metadata rows after: 16093
Player master shape: (737, 13)

,player,cricsheet_id,match_type,cricinfo_id,unique_name,full_name,name,country,dob,batting_style,bowling_style,birthplace,playing_role
0,A Ashish Reddy,1c2a64cd,name,389605.0,A Ashish Reddy,Ammana Ashish Reddy,NaN,India,1991-02-24,Right hand Bat,Right arm Medium,Secunderabad,Allrounder
1,A Badoni,872b03f7,name,1151270.0,A Badoni,Ayush Badoni,NaN,India,1999-12-03,Right hand Bat,Right arm Offbreak,Delhi,Batter
2,A Chandila,99b202b3,name,27783.0,A Chandila,Ajit Chandila,NaN,India,1983-12-05,Right hand Bat,Right arm Offbreak,"Faridabad, Haryana",Allrounder
3,A Chopra,57a7b064,name,53910.0,Anjum Chopra,Anjum Chopra,NaN,India,1977-05-20,Left hand Bat,Right arm Medium,New Delhi,NaN
4,A Choudhary,18e6906e,name,527299.0,A Choudhary,Aniket Vinod Choudhary,NaN,India,1990-01-28,Right hand Bat,Left arm Medium,"Bikaner, Rajasthan",Bowler
5,A Dananjaya,5b16a806,name,574178.0,A Dananjaya,Mahamarakkala Kurukulasooriya Patabendige Akil...,NaN,Sri Lanka,1993-10-04,Left hand Bat,"Right arm Offbreak, Legbreak",Panadura,Allrounder
6,A Flintoff,ddc0828d,name,12856.0,A Flintoff,Andrew Flintoff,NaN,England,1977-12-06,Right hand Bat,Right arm Fast medium,"Preston, Lancashire",Allrounder
7,A Kamboj,fcc21ace,name,1175428.0,A Kamboj,Anshul Kamboj,NaN,India,2000-12-06,Right hand Bat,Right arm Medium,"Karnal, Haryana",Allrounder
8,A Kumble,0c2730df,name,30176.0,A Kumble,Anil Kumble,NaN,India,1970-10-17,Right hand Bat,Legbreak Googly,"Bangalore, Karnataka",Bowler
9,A Manohar,0890552f,name,778963.0,A Manohar,Abhinav Manohar,NaN,India,1994-09-16,Right hand Bat,Legbreak Googly,"Bangalore, Karnataka",Batting Allrounder
10,A Mhatre,b2b4f545,name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,A Mishra,54690147,name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,A Mithun,66cf56a5,name,310958.0,A Mithun,Abhimanyu Mithun,NaN,India,1989-10-25,Right hand Bat,Right arm Medium,Bangalore,Bowler
13,A Mukund,6165bca6,name,302582.0,A Mukund,Abhinav Mukund,NaN,India,1990-01-06,Left hand Bat,Legbreak Googly,"Madras (now Chennai), Tamil Nadu",Top order Batter
14,A Nehra,96fd40ae,name,31820.0,A Nehra,Ashish Nehra,NaN,India,1979-04-29,Right hand Bat,Left arm Medium fast,Delhi,Bowler
15,A Nortje,acdc62f5,name,481979.0,A Nortje,Anrich Arno Nortje,NaN,South Africa,1993-11-16,Right hand Bat,Right arm Fast,NaN,Bowler
16,A Raghuvanshi,d7017798,name,1292495.0,A Raghuvanshi,Angkrish Raghuvanshi,Angkrish Raghuvanshi,India,2004-06-05,Right-hand bat,Slow left-arm orthodox,NaN,NaN
17,A Singh,5b040b81,name,26789.0,A Singh,Amit Singh,NaN,India,1981-06-21,Right hand Bat,Right arm Medium fast,"Bidar, Karnataka",Bowler
18,A Symonds,bd77eb62,name,7702.0,A Symonds,Andrew Symonds,NaN,Australia,1975-06-09,Right hand Bat,"Right arm Medium, Right arm Offbreak","Birmingham, Warwickshire, England",Allrounder
19,A Tomar,aa5d8c9e,name,1081183.0,A Tomar,Abhijeet Tomar,NaN,India,1995-03-14,Right hand Bat,Right arm Offbreak,"Jaipur, Rajasthan",Opening Batter

In [ ]:
print("Unique players:", player_master["cricsheet_id"].nunique())
print("Rows:", len(player_master))

print("\nMissing metadata:")
display(
    player_master[
        [
            "full_name",
            "country",
            "dob",
            "batting_style",
            "bowling_style",
            "playing_role"
        ]
    ].isna().sum()
) 
display(
    player_master[
        player_master["cricsheet_id"] == "12314277"
    ]
)

Unique players: 737
Rows: 737

Missing metadata:

full_name        27
country          26
dob              27
batting_style    27
bowling_style    97
playing_role     99
dtype: int64

,player,cricsheet_id,match_type,cricinfo_id,unique_name,full_name,name,country,dob,batting_style,bowling_style,birthplace,playing_role
86,Arshad Khan,12314277,name,1244751.0,Arshad Khan (2),Mohd Arshad Khan,NaN,India,1997-12-20,Left hand Bat,Left arm Medium,Gopalganj (Seoni),Bowler

In [ ]:
output_path = r"C:\stuff\DATA MINING PROJECT\data\processed\ipl\player_master.csv"

player_master.to_csv(output_path, index=False)

print("Player master saved successfully!")
print(output_path)
print("Rows:", len(player_master))
print("Columns:", len(player_master.columns))

Player master saved successfully!
C:\stuff\DATA MINING PROJECT\data\processed\ipl\player_master.csv
Rows: 737
Columns: 13

In [ ]:
check = pd.read_csv(output_path)

print(check.shape)
display(check.head())

(737, 13)

,player,cricsheet_id,match_type,cricinfo_id,unique_name,full_name,name,country,dob,batting_style,bowling_style,birthplace,playing_role
0,A Ashish Reddy,1c2a64cd,name,389605.0,A Ashish Reddy,Ammana Ashish Reddy,NaN,India,1991-02-24,Right hand Bat,Right arm Medium,Secunderabad,Allrounder
1,A Badoni,872b03f7,name,1151270.0,A Badoni,Ayush Badoni,NaN,India,1999-12-03,Right hand Bat,Right arm Offbreak,Delhi,Batter
2,A Chandila,99b202b3,name,27783.0,A Chandila,Ajit Chandila,NaN,India,1983-12-05,Right hand Bat,Right arm Offbreak,"Faridabad, Haryana",Allrounder
3,A Chopra,57a7b064,name,53910.0,Anjum Chopra,Anjum Chopra,NaN,India,1977-05-20,Left hand Bat,Right arm Medium,New Delhi,NaN
4,A Choudhary,18e6906e,name,527299.0,A Choudhary,Aniket Vinod Choudhary,NaN,India,1990-01-28,Right hand Bat,Left arm Medium,"Bikaner, Rajasthan",Bowler

In [20]:
import pandas as pd

# Paths relative to notebooks/season_features.ipynb
batting_path = "../data/processed/ipl/batting_match.csv"
bowling_path = "../data/processed/ipl/bowling_match.csv"

batting = pd.read_csv(batting_path)
bowling = pd.read_csv(bowling_path)

print("Batting data:", batting.shape)
print("Bowling data:", bowling.shape)

Batting data: (18768, 11)
Bowling data: (14700, 13)

In [21]:
print("IPL seasons:")
print(sorted(batting["season"].unique()))

print("\nNumber of seasons:", batting["season"].nunique())

print("\nBatting records by season:")
display(
    batting.groupby("season")
    .size()
    .reset_index(name="records")
)

IPL seasons:
['2007/08', '2009', '2009/10', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020/21', '2021', '2022', '2023', '2024', '2025', '2026']

Number of seasons: 19

Batting records by season:

     season  records
0   2007/08      881
1      2009      875
2   2009/10      917
3      2011     1055
4      2012     1108
5      2013     1162
6      2014      873
7      2015      881
8      2016      865
9      2017      898
10     2018      905
11     2019      874
12  2020/21      868
13     2021      909
14     2022     1158
15     2023     1171
16     2024     1115
17     2025     1123
18     2026     1130

In [22]:
bowling_season = (
    bowling
    .groupby(["player", "season"], as_index=False)
    .agg(
        matches=("match_id", "nunique"),
        balls=("balls", "sum"),
        runs_conceded=("runs_conceded", "sum"),
        wickets=("wickets", "sum")
    )
)

bowling_season["overs"] = (
    bowling_season["balls"] / 6
)

bowling_season["economy"] = (
    bowling_season["runs_conceded"] /
    bowling_season["overs"]
)

bowling_season["bowling_strike_rate"] = (
    bowling_season["balls"] /
    bowling_season["wickets"]
)

display(bowling_season.head(20))

,player,season,matches,balls,runs_conceded,wickets,overs,economy,bowling_strike_rate
0,A Ashish Reddy,2012,9,163,237,11,27.166667,8.723926,14.818182
1,A Ashish Reddy,2013,5,40,70,3,6.666667,10.500000,13.333333
2,A Ashish Reddy,2015,4,36,50,3,6.000000,8.333333,12.000000
3,A Ashish Reddy,2016,2,23,39,1,3.833333,10.173913,23.000000
4,A Badoni,2022,2,12,11,2,2.000000,5.500000,6.000000
5,A Badoni,2023,1,1,0,0,0.166667,0.000000,inf
6,A Badoni,2024,2,12,25,0,2.000000,12.500000,inf
7,A Badoni,2025,2,10,13,2,1.666667,7.800000,5.000000
8,A Badoni,2026,1,6,14,0,1.000000,14.000000,inf
9,A Chandila,2012,4,84,86,5,14.000000,6.142857,16.800000
10,A Chandila,2013,8,150,156,6,25.000000,6.240000,25.000000
11,A Choudhary,2017,5,101,144,5,16.833333,8.554455,20.200000
12,A Dananjaya,2018,1,24,47,0,4.000000,11.750000,inf
13,A Flintoff,2009,3,66,105,2,11.000000,9.545455,33.000000
14,A Kamboj,2024,3,60,114,2,10.000000,11.400000,30.000000
15,A Kamboj,2025,8,129,172,8,21.500000,8.000000,16.125000
16,A Kamboj,2026,14,302,530,21,50.333333,10.529801,14.380952
17,A Kumble,2007/08,10,230,304,7,38.333333,7.930435,32.857143
18,A Kumble,2009,16,355,347,21,59.166667,5.864789,16.904762
19,A Kumble,2009/10,16,380,407,17,63.333333,6.426316,22.352941

In [23]:
print(
    "Zero-wicket bowling records:",
    (bowling_season["wickets"] == 0).sum()
)

print(
    "Missing bowling strike rates:",
    bowling_season["bowling_strike_rate"].isna().sum()
)

Zero-wicket bowling records: 390
Missing bowling strike rates: 0

In [24]:
# Keep only the most recent 5 IPL seasons

recent_seasons = ["2021", "2022", "2023", "2024", "2025"]

batting = batting[
    batting["season"].astype(str).isin(recent_seasons)
].copy()

bowling = bowling[
    bowling["season"].astype(str).isin(recent_seasons)
].copy()

print("Seasons being used:")
print(sorted(batting["season"].unique()))

print("\nBatting shape:", batting.shape)
print("Bowling shape:", bowling.shape)

Seasons being used:
['2021', '2022', '2023', '2024', '2025']

Batting shape: (5476, 11)
Bowling shape: (4179, 13)

In [25]:
print("Batting records by season:")
display(
    batting.groupby("season")
    .size()
    .reset_index(name="records")
)

print("\nBowling records by season:")
display(
    bowling.groupby("season")
    .size()
    .reset_index(name="records")
)

Batting records by season:

  season  records
0   2021      909
1   2022     1158
2   2023     1171
3   2024     1115
4   2025     1123

Bowling records by season:

  season  records
0   2021      699
1   2022      857
2   2023      898
3   2024      857
4   2025      868

In [26]:
# ============================================
# BATTING FEATURES — 5 RECENT IPL SEASONS
# ============================================

batting_season = (
    batting
    .groupby(["player", "season"], as_index=False)
    .agg(
        batting_matches=("match_id", "nunique"),
        runs=("runs", "sum"),
        balls=("balls", "sum"),
        fours=("fours", "sum"),
        sixes=("sixes", "sum")
    )
)

# Strike rate
batting_season["strike_rate"] = (
    batting_season["runs"] /
    batting_season["balls"].replace(0, pd.NA)
) * 100

# Boundary runs
batting_season["boundary_runs"] = (
    batting_season["fours"] * 4 +
    batting_season["sixes"] * 6
)

# Percentage of scoring runs coming from boundaries
batting_season["boundary_percentage"] = (
    batting_season["boundary_runs"] /
    batting_season["runs"].replace(0, pd.NA)
) * 100

print("Shape:", batting_season.shape)

display(batting_season.head(20))

Shape: (837, 10)

,player,season,batting_matches,runs,balls,fours,sixes,strike_rate,boundary_runs,boundary_percentage
0,A Badoni,2022,11,161,130,11,7,123.846154,86,53.416149
1,A Badoni,2023,12,238,171,13,12,139.181287,124,52.10084
2,A Badoni,2024,12,235,171,22,5,137.426901,118,50.212766
3,A Badoni,2025,11,329,221,27,14,148.868778,192,58.358663
4,A Kamboj,2024,1,2,2,0,0,100.000000,0,0.0
5,A Kamboj,2025,5,14,12,2,0,116.666667,8,57.142857
6,A Manohar,2022,7,108,75,14,3,144.000000,74,68.518519
7,A Manohar,2023,6,114,83,6,7,137.349398,66,57.894737
8,A Manohar,2024,2,9,16,1,0,56.250000,4,44.444444
9,A Manohar,2025,5,61,61,2,4,100.000000,32,52.459016
10,A Mhatre,2025,7,240,127,31,11,188.976378,190,79.166667
11,A Mishra,2023,1,19,30,2,0,63.333333,8,42.105263
12,A Nortje,2022,1,1,6,0,0,16.666667,0,0.0
13,A Nortje,2023,7,37,29,6,0,127.586207,24,64.864865
14,A Nortje,2024,2,4,8,0,0,50.000000,0,0.0
15,A Raghuvanshi,2024,7,163,105,16,8,155.238095,112,68.711656
16,A Raghuvanshi,2025,11,300,214,30,8,140.186916,168,56.0
17,A Tomar,2022,1,4,8,1,0,50.000000,4,100.0
18,A Zampa,2023,3,10,16,0,0,62.500000,0,0.0
19,AA Kulkarni,2024,2,9,8,2,0,112.500000,8,88.888889

In [27]:
print("Missing values:")
display(batting_season.isna().sum())

print("\nPlayers:", batting_season["player"].nunique())
print("Seasons:", batting_season["season"].nunique())
display(
    batting_season.sort_values(
        ["player", "season"]
    ).head(30)
)

Missing values:

player                  0
season                  0
batting_matches         0
runs                    0
balls                   0
fours                   0
sixes                   0
strike_rate             0
boundary_runs           0
boundary_percentage    46
dtype: int64

Players: 332
Seasons: 5

,player,season,batting_matches,runs,balls,fours,sixes,strike_rate,boundary_runs,boundary_percentage
0,A Badoni,2022,11,161,130,11,7,123.846154,86,53.416149
1,A Badoni,2023,12,238,171,13,12,139.181287,124,52.10084
2,A Badoni,2024,12,235,171,22,5,137.426901,118,50.212766
3,A Badoni,2025,11,329,221,27,14,148.868778,192,58.358663
4,A Kamboj,2024,1,2,2,0,0,100.000000,0,0.0
5,A Kamboj,2025,5,14,12,2,0,116.666667,8,57.142857
6,A Manohar,2022,7,108,75,14,3,144.000000,74,68.518519
7,A Manohar,2023,6,114,83,6,7,137.349398,66,57.894737
8,A Manohar,2024,2,9,16,1,0,56.250000,4,44.444444
9,A Manohar,2025,5,61,61,2,4,100.000000,32,52.459016
10,A Mhatre,2025,7,240,127,31,11,188.976378,190,79.166667
11,A Mishra,2023,1,19,30,2,0,63.333333,8,42.105263
12,A Nortje,2022,1,1,6,0,0,16.666667,0,0.0
13,A Nortje,2023,7,37,29,6,0,127.586207,24,64.864865
14,A Nortje,2024,2,4,8,0,0,50.000000,0,0.0
15,A Raghuvanshi,2024,7,163,105,16,8,155.238095,112,68.711656
16,A Raghuvanshi,2025,11,300,214,30,8,140.186916,168,56.0
17,A Tomar,2022,1,4,8,1,0,50.000000,4,100.0
18,A Zampa,2023,3,10,16,0,0,62.500000,0,0.0
19,AA Kulkarni,2024,2,9,8,2,0,112.500000,8,88.888889
20,AB de Villiers,2021,14,313,211,23,16,148.341232,188,60.063898
21,AD Russell,2021,8,183,117,14,14,156.410256,140,76.502732
22,AD Russell,2022,12,335,189,18,32,177.248677,264,78.80597
23,AD Russell,2023,14,227,155,13,18,146.451613,160,70.484581
24,AD Russell,2024,9,222,116,20,16,191.379310,176,79.279279
25,AD Russell,2025,10,167,102,16,14,163.725490,148,88.622754
26,AF Milne,2021,3,16,17,0,1,94.117647,6,37.5
27,AJ Finch,2022,5,86,61,10,3,140.983607,58,67.44186
28,AJ Hosein,2023,1,16,10,1,1,160.000000,10,62.5
29,AJ Turner,2024,2,21,18,0,2,116.666667,12,57.142857

In [ ]:
# ============================================
# BOWLING FEATURES FOR 5 RECENT IPL SEASONS
# ============================================

bowling_season = (
    bowling
    .groupby(["player", "season"], as_index=False)
    .agg(
        bowling_matches=("match_id", "nunique"),
        balls=("balls", "sum"),
        runs_conceded=("runs_conceded", "sum"),
        wickets=("wickets", "sum")
    )
)

# Overs
bowling_season["overs"] = (
    bowling_season["balls"] / 6
)

# Economy
bowling_season["economy"] = (
    bowling_season["runs_conceded"] /
    bowling_season["overs"].replace(0, pd.NA)
)

# Bowling strike rate
bowling_season["bowling_strike_rate"] = (
    bowling_season["balls"] /
    bowling_season["wickets"].replace(0, pd.NA)
)

print("Shape:", bowling_season.shape)

display(bowling_season.head(20))

Shape: (638, 9)

,player,season,bowling_matches,balls,runs_conceded,wickets,overs,economy,bowling_strike_rate
0,A Badoni,2022,2,12,11,2,2.000000,5.500000,6.0
1,A Badoni,2023,1,1,0,0,0.166667,0.000000,<NA>
2,A Badoni,2024,2,12,25,0,2.000000,12.500000,<NA>
3,A Badoni,2025,2,10,13,2,1.666667,7.800000,5.0
4,A Kamboj,2024,3,60,114,2,10.000000,11.400000,30.0
5,A Kamboj,2025,8,129,172,8,21.500000,8.000000,16.125
6,A Mishra,2021,4,84,109,6,14.000000,7.785714,14.0
7,A Mishra,2023,7,114,149,7,19.000000,7.842105,16.285714
8,A Mishra,2024,1,12,20,1,2.000000,10.000000,12.0
9,A Nortje,2021,8,182,187,12,30.333333,6.164835,15.166667
10,A Nortje,2022,6,134,217,9,22.333333,9.716418,14.888889
11,A Nortje,2023,10,240,364,10,40.000000,9.100000,24.0
12,A Nortje,2024,6,132,294,7,22.000000,13.363636,18.857143
13,A Nortje,2025,2,42,83,1,7.000000,11.857143,42.0
14,A Zampa,2023,6,132,188,8,22.000000,8.545455,16.5
15,A Zampa,2025,2,48,94,2,8.000000,11.750000,24.0
16,AD Russell,2021,8,114,188,11,19.000000,9.894737,10.363636
17,AD Russell,2022,13,169,278,17,28.166667,9.869822,9.941176
18,AD Russell,2023,9,91,172,7,15.166667,11.340659,13.0
19,AD Russell,2024,14,176,295,19,29.333333,10.056818,9.263158

In [29]:
print("Missing values:")
display(bowling_season.isna().sum())

print("\nPlayers:", bowling_season["player"].nunique())
print("Seasons:", bowling_season["season"].nunique())

Missing values:

player                   0
season                   0
bowling_matches          0
balls                    0
runs_conceded            0
wickets                  0
overs                    0
economy                  0
bowling_strike_rate    118
dtype: int64

Players: 253
Seasons: 5