In [1]:
import pandas as pd
import numpy as np

features_path = r"C:\stuff\DATA MINING PROJECT\data\processed\ipl\player_season_features.csv"

df = pd.read_csv(features_path)

print("Shape:", df.shape)
print("Players:", df["player"].nunique())
print("Seasons:", sorted(df["season"].unique()))

display(df.head())

Shape: (1010, 17)
Players: 384
Seasons: [np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025), np.int64(2026)]

,player,season,batting_matches,runs,batting_balls,fours,sixes,strike_rate,boundary_runs,boundary_percentage,bowling_matches,bowling_balls,runs_conceded,wickets,overs,economy,bowling_strike_rate
0,A Badoni,2022,11.0,161.0,130.0,11.0,7.0,123.846154,86.0,53.416149,2.0,12.0,11.0,2.0,2.000000,5.5,6.0
1,A Badoni,2023,12.0,238.0,171.0,13.0,12.0,139.181287,124.0,52.100840,1.0,1.0,0.0,0.0,0.166667,0.0,NaN
2,A Badoni,2024,12.0,235.0,171.0,22.0,5.0,137.426901,118.0,50.212766,2.0,12.0,25.0,0.0,2.000000,12.5,NaN
3,A Badoni,2025,11.0,329.0,221.0,27.0,14.0,148.868778,192.0,58.358663,2.0,10.0,13.0,2.0,1.666667,7.8,5.0
4,A Badoni,2026,10.0,215.0,141.0,23.0,9.0,152.482270,146.0,67.906977,1.0,6.0,14.0,0.0,1.000000,14.0,NaN

In [2]:
# ============================================
# LATEST SEASON PERFORMANCE
# ============================================

latest_season = df["season"].max()

latest = (
    df[df["season"] == latest_season]
    .copy()
)

print("Latest season:", latest_season)
print("Players in latest season:", latest["player"].nunique())

display(latest.head(20))

Latest season: 2026
Players in latest season: 202

,player,season,batting_matches,runs,batting_balls,fours,sixes,strike_rate,boundary_runs,boundary_percentage,bowling_matches,bowling_balls,runs_conceded,wickets,overs,economy,bowling_strike_rate
4,A Badoni,2026,10.0,215.0,141.0,23.0,9.0,152.482270,146.0,67.906977,1.0,6.0,14.0,0.0,1.000000,14.000000,NaN
7,A Kamboj,2026,4.0,58.0,36.0,3.0,4.0,161.111111,36.0,62.068966,14.0,302.0,530.0,21.0,50.333333,10.529801,14.380952
13,A Mhatre,2026,6.0,201.0,112.0,20.0,12.0,179.464286,152.0,75.621891,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
20,A Nortje,2026,1.0,0.0,1.0,0.0,0.0,0.000000,0.0,NaN,1.0,24.0,39.0,0.0,4.000000,9.750000,NaN
23,A Raghuvanshi,2026,12.0,422.0,287.0,40.0,19.0,147.038328,274.0,64.928910,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
28,AA Kulkarni,2026,2.0,17.0,25.0,1.0,0.0,68.000000,4.0,23.529412,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
34,AF Milne,2026,1.0,2.0,2.0,0.0,0.0,100.000000,0.0,0.000000,1.0,20.0,41.0,0.0,3.333333,12.300000,NaN
37,AJ Hosein,2026,2.0,5.0,3.0,0.0,0.0,166.666667,0.0,0.000000,7.0,148.0,198.0,8.0,24.666667,8.027027,18.500000
44,AK Markram,2026,11.0,231.0,166.0,20.0,11.0,139.156627,146.0,63.203463,5.0,36.0,83.0,0.0,6.000000,13.833333,NaN
45,AM Ghazanfar,2026,1.0,2.0,3.0,0.0,0.0,66.666667,0.0,0.000000,11.0,233.0,389.0,15.0,38.833333,10.017167,15.533333
50,AM Rahane,2026,14.0,335.0,248.0,25.0,18.0,135.080645,208.0,62.089552,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
55,AR Patel,2026,11.0,173.0,131.0,16.0,6.0,132.061069,100.0,57.803468,13.0,264.0,360.0,11.0,44.000000,8.181818,24.000000
63,AS Roy,2026,7.0,52.0,39.0,3.0,2.0,133.333333,24.0,46.153846,12.0,163.0,261.0,9.0,27.166667,9.607362,18.111111
72,Abdul Samad,2026,7.0,116.0,88.0,10.0,5.0,131.818182,70.0,60.344828,1.0,1.0,6.0,0.0,0.166667,36.000000,NaN
73,Abhinandan Singh,2026,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,3.0,58.0,122.0,3.0,9.666667,12.620690,19.333333
78,Abhishek Sharma,2026,15.0,563.0,275.0,50.0,43.0,204.727273,458.0,81.349911,4.0,29.0,49.0,0.0,4.833333,10.137931,NaN
82,Abishek Porel,2026,4.0,108.0,88.0,15.0,1.0,122.727273,66.0,61.111111,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
92,Akash Singh,2026,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,2.0,42.0,80.0,4.0,7.000000,11.428571,10.500000
93,Akshat Raghuwanshi,2026,2.0,29.0,25.0,1.0,1.0,116.000000,10.0,34.482759,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
97,Aniket Verma,2026,8.0,79.0,54.0,6.0,5.0,146.296296,54.0,68.354430,0.0,0.0,0.0,0.0,0.000000,NaN,NaN

In [3]:
# ============================================
# LATEST SEASON FEATURES
# ============================================

latest_features = latest[
    [
        "player",
        "runs",
        "strike_rate",
        "fours",
        "sixes",
        "boundary_percentage",
        "wickets",
        "economy",
        "bowling_strike_rate"
    ]
].copy()

latest_features = latest_features.rename(
    columns={
        "runs": "latest_runs",
        "strike_rate": "latest_strike_rate",
        "fours": "latest_fours",
        "sixes": "latest_sixes",
        "boundary_percentage": "latest_boundary_percentage",
        "wickets": "latest_wickets",
        "economy": "latest_economy",
        "bowling_strike_rate": "latest_bowling_strike_rate"
    }
)

display(latest_features.head(20))

,player,latest_runs,latest_strike_rate,latest_fours,latest_sixes,latest_boundary_percentage,latest_wickets,latest_economy,latest_bowling_strike_rate
4,A Badoni,215.0,152.482270,23.0,9.0,67.906977,0.0,14.000000,NaN
7,A Kamboj,58.0,161.111111,3.0,4.0,62.068966,21.0,10.529801,14.380952
13,A Mhatre,201.0,179.464286,20.0,12.0,75.621891,0.0,NaN,NaN
20,A Nortje,0.0,0.000000,0.0,0.0,NaN,0.0,9.750000,NaN
23,A Raghuvanshi,422.0,147.038328,40.0,19.0,64.928910,0.0,NaN,NaN
28,AA Kulkarni,17.0,68.000000,1.0,0.0,23.529412,0.0,NaN,NaN
34,AF Milne,2.0,100.000000,0.0,0.0,0.000000,0.0,12.300000,NaN
37,AJ Hosein,5.0,166.666667,0.0,0.0,0.000000,8.0,8.027027,18.500000
44,AK Markram,231.0,139.156627,20.0,11.0,63.203463,0.0,13.833333,NaN
45,AM Ghazanfar,2.0,66.666667,0.0,0.0,0.000000,15.0,10.017167,15.533333
50,AM Rahane,335.0,135.080645,25.0,18.0,62.089552,0.0,NaN,NaN
55,AR Patel,173.0,132.061069,16.0,6.0,57.803468,11.0,8.181818,24.000000
63,AS Roy,52.0,133.333333,3.0,2.0,46.153846,9.0,9.607362,18.111111
72,Abdul Samad,116.0,131.818182,10.0,5.0,60.344828,0.0,36.000000,NaN
73,Abhinandan Singh,0.0,NaN,0.0,0.0,NaN,3.0,12.620690,19.333333
78,Abhishek Sharma,563.0,204.727273,50.0,43.0,81.349911,0.0,10.137931,NaN
82,Abishek Porel,108.0,122.727273,15.0,1.0,61.111111,0.0,NaN,NaN
92,Akash Singh,0.0,NaN,0.0,0.0,NaN,4.0,11.428571,10.500000
93,Akshat Raghuwanshi,29.0,116.000000,1.0,1.0,34.482759,0.0,NaN,NaN
97,Aniket Verma,79.0,146.296296,6.0,5.0,68.354430,0.0,NaN,NaN

In [4]:
# ============================================
# 3-SEASON RECENT PERFORMANCE
# ============================================

recent_3 = (
    df
    .sort_values(["player", "season"])
    .groupby("player")
    .tail(3)
)

print("Rows:", len(recent_3))
print("Players:", recent_3["player"].nunique())

display(
    recent_3
    .sort_values(["player", "season"])
    .head(20)
)

Rows: 817
Players: 384

,player,season,batting_matches,runs,batting_balls,fours,sixes,strike_rate,boundary_runs,boundary_percentage,bowling_matches,bowling_balls,runs_conceded,wickets,overs,economy,bowling_strike_rate
2,A Badoni,2024,12.0,235.0,171.0,22.0,5.0,137.426901,118.0,50.212766,2.0,12.0,25.0,0.0,2.000000,12.500000,NaN
3,A Badoni,2025,11.0,329.0,221.0,27.0,14.0,148.868778,192.0,58.358663,2.0,10.0,13.0,2.0,1.666667,7.800000,5.000000
4,A Badoni,2026,10.0,215.0,141.0,23.0,9.0,152.482270,146.0,67.906977,1.0,6.0,14.0,0.0,1.000000,14.000000,NaN
5,A Kamboj,2024,1.0,2.0,2.0,0.0,0.0,100.000000,0.0,0.000000,3.0,60.0,114.0,2.0,10.000000,11.400000,30.000000
6,A Kamboj,2025,5.0,14.0,12.0,2.0,0.0,116.666667,8.0,57.142857,8.0,129.0,172.0,8.0,21.500000,8.000000,16.125000
7,A Kamboj,2026,4.0,58.0,36.0,3.0,4.0,161.111111,36.0,62.068966,14.0,302.0,530.0,21.0,50.333333,10.529801,14.380952
9,A Manohar,2023,6.0,114.0,83.0,6.0,7.0,137.349398,66.0,57.894737,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
10,A Manohar,2024,2.0,9.0,16.0,1.0,0.0,56.250000,4.0,44.444444,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
11,A Manohar,2025,5.0,61.0,61.0,2.0,4.0,100.000000,32.0,52.459016,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
12,A Mhatre,2025,7.0,240.0,127.0,31.0,11.0,188.976378,190.0,79.166667,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
13,A Mhatre,2026,6.0,201.0,112.0,20.0,12.0,179.464286,152.0,75.621891,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
14,A Mishra,2023,1.0,19.0,30.0,2.0,0.0,63.333333,8.0,42.105263,7.0,114.0,149.0,7.0,19.000000,7.842105,16.285714
15,A Mishra,2024,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,1.0,12.0,20.0,1.0,2.000000,10.000000,12.000000
18,A Nortje,2024,2.0,4.0,8.0,0.0,0.0,50.000000,0.0,0.000000,6.0,132.0,294.0,7.0,22.000000,13.363636,18.857143
19,A Nortje,2025,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,2.0,42.0,83.0,1.0,7.000000,11.857143,42.000000
20,A Nortje,2026,1.0,0.0,1.0,0.0,0.0,0.000000,0.0,NaN,1.0,24.0,39.0,0.0,4.000000,9.750000,NaN
21,A Raghuvanshi,2024,7.0,163.0,105.0,16.0,8.0,155.238095,112.0,68.711656,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
22,A Raghuvanshi,2025,11.0,300.0,214.0,30.0,8.0,140.186916,168.0,56.000000,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
23,A Raghuvanshi,2026,12.0,422.0,287.0,40.0,19.0,147.038328,274.0,64.928910,0.0,0.0,0.0,0.0,0.000000,NaN,NaN
24,A Tomar,2022,1.0,4.0,8.0,1.0,0.0,50.000000,4.0,100.000000,0.0,0.0,0.0,0.0,0.000000,NaN,NaN

In [5]:
# ============================================
# 3-SEASON AGGREGATE FEATURES
# ============================================

recent_3_features = (
    recent_3
    .groupby("player", as_index=False)
    .agg(
        recent_3_seasons=("season", "nunique"),

        recent_3_runs=("runs", "sum"),
        recent_3_balls=("batting_balls", "sum"),
        recent_3_fours=("fours", "sum"),
        recent_3_sixes=("sixes", "sum"),

        recent_3_wickets=("wickets", "sum"),
        recent_3_bowling_balls=("bowling_balls", "sum"),
        recent_3_runs_conceded=("runs_conceded", "sum")
    )
)

# 3-season batting strike rate
recent_3_features["recent_3_strike_rate"] = (
    recent_3_features["recent_3_runs"] /
    recent_3_features["recent_3_balls"].replace(0, np.nan)
) * 100

# 3-season bowling economy
recent_3_features["recent_3_economy"] = (
    recent_3_features["recent_3_runs_conceded"] /
    (recent_3_features["recent_3_bowling_balls"] / 6).replace(0, np.nan)
)

# 3-season bowling strike rate
recent_3_features["recent_3_bowling_strike_rate"] = (
    recent_3_features["recent_3_bowling_balls"] /
    recent_3_features["recent_3_wickets"].replace(0, np.nan)
)

display(recent_3_features.head(20))

,player,recent_3_seasons,recent_3_runs,recent_3_balls,recent_3_fours,recent_3_sixes,recent_3_wickets,recent_3_bowling_balls,recent_3_runs_conceded,recent_3_strike_rate,recent_3_economy,recent_3_bowling_strike_rate
0,A Badoni,3,779.0,533.0,72.0,28.0,2.0,28.0,52.0,146.153846,11.142857,14.000000
1,A Kamboj,3,74.0,50.0,5.0,4.0,31.0,491.0,816.0,148.000000,9.971487,15.838710
2,A Manohar,3,184.0,160.0,9.0,11.0,0.0,0.0,0.0,115.000000,NaN,NaN
3,A Mhatre,2,441.0,239.0,51.0,23.0,0.0,0.0,0.0,184.518828,NaN,NaN
4,A Mishra,2,19.0,30.0,2.0,0.0,8.0,126.0,169.0,63.333333,8.047619,15.750000
5,A Nortje,3,4.0,9.0,0.0,0.0,8.0,198.0,416.0,44.444444,12.606061,24.750000
6,A Raghuvanshi,3,885.0,606.0,86.0,35.0,0.0,0.0,0.0,146.039604,NaN,NaN
7,A Tomar,1,4.0,8.0,1.0,0.0,0.0,0.0,0.0,50.000000,NaN,NaN
8,A Zampa,2,10.0,16.0,0.0,0.0,10.0,180.0,282.0,62.500000,9.400000,18.000000
9,AA Kulkarni,2,26.0,33.0,3.0,0.0,0.0,0.0,0.0,78.787879,NaN,NaN
10,AD Russell,3,616.0,373.0,49.0,48.0,34.0,376.0,684.0,165.147453,10.914894,11.058824
11,AF Milne,2,2.0,2.0,0.0,0.0,0.0,35.0,60.0,100.000000,10.285714,NaN
12,AJ Finch,1,86.0,61.0,10.0,3.0,0.0,0.0,0.0,140.983607,NaN,NaN
13,AJ Hosein,2,21.0,13.0,1.0,1.0,9.0,172.0,238.0,161.538462,8.302326,19.111111
14,AJ Turner,1,21.0,18.0,0.0,2.0,0.0,0.0,0.0,116.666667,NaN,NaN
15,AJ Tye,1,0.0,0.0,0.0,0.0,2.0,66.0,107.0,NaN,9.727273,33.000000
16,AK Markram,3,896.0,639.0,76.0,37.0,4.0,114.0,200.0,140.219092,10.526316,28.500000
17,AM Ghazanfar,1,2.0,3.0,0.0,0.0,15.0,233.0,389.0,66.666667,10.017167,15.533333
18,AM Rahane,3,967.0,708.0,85.0,45.0,0.0,0.0,0.0,136.581921,NaN,NaN
19,AR Patel,3,671.0,477.0,58.0,31.0,27.0,744.0,1010.0,140.670860,8.145161,27.555556

In [6]:
print("Shape:", recent_3_features.shape)

print("\nMissing values:")
display(recent_3_features.isna().sum())

Shape: (384, 12)

Missing values:

player                            0
recent_3_seasons                  0
recent_3_runs                     0
recent_3_balls                    0
recent_3_fours                    0
recent_3_sixes                    0
recent_3_wickets                  0
recent_3_bowling_balls            0
recent_3_runs_conceded            0
recent_3_strike_rate             42
recent_3_economy                128
recent_3_bowling_strike_rate    172
dtype: int64

In [7]:
# ============================================
# PERFORMANCE TREND
# ============================================

df_sorted = df.sort_values(["player", "season"]).copy()

first_last = (
    df_sorted
    .groupby("player")
    .agg(
        first_season=("season", "min"),
        latest_season=("season", "max"),
        first_runs=("runs", "first"),
        latest_runs_from_history=("runs", "last"),
        first_strike_rate=("strike_rate", "first"),
        latest_strike_rate_from_history=("strike_rate", "last"),
        first_wickets=("wickets", "first"),
        latest_wickets_from_history=("wickets", "last"),
        first_economy=("economy", "first"),
        latest_economy_from_history=("economy", "last")
    )
    .reset_index()
)

# Batting run trend
first_last["runs_trend"] = (
    first_last["latest_runs_from_history"] -
    first_last["first_runs"]
)

# Strike-rate trend
first_last["strike_rate_trend"] = (
    first_last["latest_strike_rate_from_history"] -
    first_last["first_strike_rate"]
)

# Wicket trend
first_last["wickets_trend"] = (
    first_last["latest_wickets_from_history"] -
    first_last["first_wickets"]
)

# Economy trend
# Lower economy is better, so improvement is represented as positive
first_last["economy_trend"] = (
    first_last["first_economy"] -
    first_last["latest_economy_from_history"]
)

display(first_last.head(20))

,player,first_season,latest_season,first_runs,latest_runs_from_history,first_strike_rate,latest_strike_rate_from_history,first_wickets,latest_wickets_from_history,first_economy,latest_economy_from_history,runs_trend,strike_rate_trend,wickets_trend,economy_trend
0,A Badoni,2022,2026,161.0,215.0,123.846154,152.482270,2.0,0.0,5.500000,14.000000,54.0,28.636116,-2.0,-8.500000
1,A Kamboj,2024,2026,2.0,58.0,100.000000,161.111111,2.0,21.0,11.400000,10.529801,56.0,61.111111,19.0,0.870199
2,A Manohar,2022,2025,108.0,61.0,144.000000,100.000000,0.0,0.0,NaN,NaN,-47.0,-44.000000,0.0,NaN
3,A Mhatre,2025,2026,240.0,201.0,188.976378,179.464286,0.0,0.0,NaN,NaN,-39.0,-9.512092,0.0,NaN
4,A Mishra,2023,2024,19.0,0.0,63.333333,63.333333,7.0,1.0,7.842105,10.000000,-19.0,0.000000,-6.0,-2.157895
5,A Nortje,2022,2026,1.0,0.0,16.666667,0.000000,9.0,0.0,9.716418,9.750000,-1.0,-16.666667,-9.0,-0.033582
6,A Raghuvanshi,2024,2026,163.0,422.0,155.238095,147.038328,0.0,0.0,NaN,NaN,259.0,-8.199768,0.0,NaN
7,A Tomar,2022,2022,4.0,4.0,50.000000,50.000000,0.0,0.0,NaN,NaN,0.0,0.000000,0.0,NaN
8,A Zampa,2023,2025,10.0,0.0,62.500000,62.500000,8.0,2.0,8.545455,11.750000,-10.0,0.000000,-6.0,-3.204545
9,AA Kulkarni,2024,2026,9.0,17.0,112.500000,68.000000,0.0,0.0,NaN,NaN,8.0,-44.500000,0.0,NaN
10,AD Russell,2022,2025,335.0,167.0,177.248677,163.725490,17.0,8.0,9.869822,11.944954,-168.0,-13.523187,-9.0,-2.075132
11,AF Milne,2022,2026,0.0,2.0,100.000000,100.000000,0.0,0.0,7.600000,12.300000,2.0,0.000000,0.0,-4.700000
12,AJ Finch,2022,2022,86.0,86.0,140.983607,140.983607,0.0,0.0,NaN,NaN,0.0,0.000000,0.0,NaN
13,AJ Hosein,2023,2026,16.0,5.0,160.000000,166.666667,1.0,8.0,10.000000,8.027027,-11.0,6.666667,7.0,1.972973
14,AJ Turner,2024,2024,21.0,21.0,116.666667,116.666667,0.0,0.0,NaN,NaN,0.0,0.000000,0.0,NaN
15,AJ Tye,2022,2022,0.0,0.0,NaN,NaN,2.0,2.0,9.727273,9.727273,0.0,NaN,0.0,0.000000
16,AK Markram,2022,2026,381.0,231.0,139.560440,139.156627,1.0,0.0,10.666667,13.833333,-150.0,-0.403813,-1.0,-3.166667
17,AM Ghazanfar,2026,2026,2.0,2.0,66.666667,66.666667,15.0,15.0,10.017167,10.017167,0.0,0.000000,0.0,0.000000
18,AM Rahane,2022,2026,133.0,335.0,103.906250,135.080645,0.0,0.0,NaN,NaN,202.0,31.174395,0.0,NaN
19,AR Patel,2022,2026,182.0,173.0,151.666667,132.061069,6.0,11.0,7.465116,8.181818,-9.0,-19.605598,5.0,-0.716702

In [8]:
# ============================================
# BATTING CONSISTENCY
# ============================================

batting_consistency = (
    df
    .groupby("player", as_index=False)
    .agg(
        runs_std=("runs", "std"),
        strike_rate_std=("strike_rate", "std")
    )
)

display(batting_consistency.head(20))# ============================================
# BATTING CONSISTENCY
# ============================================

batting_consistency = (
    df
    .groupby("player", as_index=False)
    .agg(
        runs_std=("runs", "std"),
        strike_rate_std=("strike_rate", "std")
    )
)

display(batting_consistency.head(20))

           player    runs_std  strike_rate_std
0        A Badoni   60.661355        11.203217
1        A Kamboj   29.484459        31.590226
2       A Manohar   48.805737        40.379910
3        A Mhatre   27.577164         6.726065
4        A Mishra   13.435029              NaN
5        A Nortje   16.071714        56.634716
6   A Raghuvanshi  129.572374         7.535649
7         A Tomar         NaN              NaN
8         A Zampa    7.071068              NaN
9     AA Kulkarni    5.656854        31.466252
10     AD Russell   70.301138        19.176003
11       AF Milne    1.414214              NaN
12       AJ Finch         NaN              NaN
13      AJ Hosein    7.778175         4.714045
14      AJ Turner         NaN              NaN
15         AJ Tye         NaN              NaN
16     AK Markram  101.643987        10.103424
17   AM Ghazanfar         NaN              NaN
18      AM Rahane  100.198303        25.764596
19       AR Patel   48.571597        11.684454

           player    runs_std  strike_rate_std
0        A Badoni   60.661355        11.203217
1        A Kamboj   29.484459        31.590226
2       A Manohar   48.805737        40.379910
3        A Mhatre   27.577164         6.726065
4        A Mishra   13.435029              NaN
5        A Nortje   16.071714        56.634716
6   A Raghuvanshi  129.572374         7.535649
7         A Tomar         NaN              NaN
8         A Zampa    7.071068              NaN
9     AA Kulkarni    5.656854        31.466252
10     AD Russell   70.301138        19.176003
11       AF Milne    1.414214              NaN
12       AJ Finch         NaN              NaN
13      AJ Hosein    7.778175         4.714045
14      AJ Turner         NaN              NaN
15         AJ Tye         NaN              NaN
16     AK Markram  101.643987        10.103424
17   AM Ghazanfar         NaN              NaN
18      AM Rahane  100.198303        25.764596
19       AR Patel   48.571597        11.684454

In [9]:
# ============================================
# BOWLING CONSISTENCY
# ============================================

bowling_consistency = (
    df
    .groupby("player", as_index=False)
    .agg(
        wickets_std=("wickets", "std"),
        economy_std=("economy", "std")
    )

)

display(bowling_consistency.head(20))

           player  wickets_std  economy_std
0        A Badoni     1.095445     5.624322
1        A Kamboj     9.712535     1.766217
2       A Manohar     0.000000          NaN
3        A Mhatre     0.000000          NaN
4        A Mishra     4.242641     1.525862
5        A Nortje     4.615192     1.792162
6   A Raghuvanshi     0.000000          NaN
7         A Tomar          NaN          NaN
8         A Zampa     4.242641     2.265956
9     AA Kulkarni     0.000000          NaN
10     AD Russell     6.130525     1.003451
11       AF Milne     0.000000     3.323402
12       AJ Finch          NaN          NaN
13      AJ Hosein     4.949747     1.395103
14      AJ Turner          NaN          NaN
15         AJ Tye          NaN          NaN
16     AK Markram     1.643168     2.447130
17   AM Ghazanfar          NaN          NaN
18      AM Rahane     0.000000          NaN
19       AR Patel     3.033150     0.600153

In [10]:
print("Trend table:", first_last.shape)
print("Batting consistency:", batting_consistency.shape)
print("Bowling consistency:", bowling_consistency.shape)

print("\nTrend missing values:")
display(first_last.isna().sum())

Trend table: (384, 15)
Batting consistency: (384, 3)
Bowling consistency: (384, 3)

Trend missing values:

player                               0
first_season                         0
latest_season                        0
first_runs                           0
latest_runs_from_history             0
first_strike_rate                   41
latest_strike_rate_from_history     41
first_wickets                        0
latest_wickets_from_history          0
first_economy                      122
latest_economy_from_history        122
runs_trend                           0
strike_rate_trend                   41
wickets_trend                        0
economy_trend                      122
dtype: int64

In [11]:
# ============================================
# PER-MATCH PERFORMANCE
# ============================================

df["runs_per_match"] = (
    df["runs"] /
    df["batting_matches"].replace(0, np.nan)
)

df["wickets_per_match"] = (
    df["wickets"] /
    df["bowling_matches"].replace(0, np.nan)
)

display(
    df[
        [
            "player",
            "season",
            "runs_per_match",
            "wickets_per_match"
        ]
    ].head(20)
)

       player  season  runs_per_match  wickets_per_match
0    A Badoni    2022       14.636364           1.000000
1    A Badoni    2023       19.833333           0.000000
2    A Badoni    2024       19.583333           0.000000
3    A Badoni    2025       29.909091           1.000000
4    A Badoni    2026       21.500000           0.000000
5    A Kamboj    2024        2.000000           0.666667
6    A Kamboj    2025        2.800000           1.000000
7    A Kamboj    2026       14.500000           1.500000
8   A Manohar    2022       15.428571                NaN
9   A Manohar    2023       19.000000                NaN
10  A Manohar    2024        4.500000                NaN
11  A Manohar    2025       12.200000                NaN
12   A Mhatre    2025       34.285714                NaN
13   A Mhatre    2026       33.500000                NaN
14   A Mishra    2023       19.000000           1.000000
15   A Mishra    2024             NaN           1.000000
16   A Nortje    2022        1.000000           1.500000
17   A Nortje    2023        5.285714           1.000000
18   A Nortje    2024        2.000000           1.166667
19   A Nortje    2025             NaN           0.500000

In [12]:
# ============================================
# PER-MATCH PERFORMANCE TREND
# ============================================

efficiency_trend = (
    df
    .sort_values(["player", "season"])
    .groupby("player")
    .agg(
        first_runs_per_match=("runs_per_match", "first"),
        latest_runs_per_match=("runs_per_match", "last"),
        first_wickets_per_match=("wickets_per_match", "first"),
        latest_wickets_per_match=("wickets_per_match", "last")
    )
    .reset_index()
)

efficiency_trend["runs_per_match_trend"] = (
    efficiency_trend["latest_runs_per_match"] -
    efficiency_trend["first_runs_per_match"]
)

efficiency_trend["wickets_per_match_trend"] = (
    efficiency_trend["latest_wickets_per_match"] -
    efficiency_trend["first_wickets_per_match"]
)

display(efficiency_trend.head(20))

,player,first_runs_per_match,latest_runs_per_match,first_wickets_per_match,latest_wickets_per_match,runs_per_match_trend,wickets_per_match_trend
0,A Badoni,14.636364,21.500000,1.000000,0.000000,6.863636,-1.000000
1,A Kamboj,2.000000,14.500000,0.666667,1.500000,12.500000,0.833333
2,A Manohar,15.428571,12.200000,NaN,NaN,-3.228571,NaN
3,A Mhatre,34.285714,33.500000,NaN,NaN,-0.785714,NaN
4,A Mishra,19.000000,19.000000,1.000000,1.000000,0.000000,0.000000
5,A Nortje,1.000000,0.000000,1.500000,0.000000,-1.000000,-1.500000
6,A Raghuvanshi,23.285714,35.166667,NaN,NaN,11.880952,NaN
7,A Tomar,4.000000,4.000000,NaN,NaN,0.000000,NaN
8,A Zampa,3.333333,3.333333,1.333333,1.000000,0.000000,-0.333333
9,AA Kulkarni,4.500000,8.500000,NaN,NaN,4.000000,NaN
10,AD Russell,27.916667,16.700000,1.307692,0.888889,-11.216667,-0.418803
11,AF Milne,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000
12,AJ Finch,17.200000,17.200000,NaN,NaN,0.000000,NaN
13,AJ Hosein,16.000000,2.500000,1.000000,1.142857,-13.500000,0.142857
14,AJ Turner,10.500000,10.500000,NaN,NaN,0.000000,NaN
15,AJ Tye,NaN,NaN,0.666667,0.666667,NaN,0.000000
16,AK Markram,31.750000,21.000000,0.250000,0.000000,-10.750000,-0.250000
17,AM Ghazanfar,2.000000,2.000000,1.363636,1.363636,0.000000,0.000000
18,AM Rahane,19.000000,23.928571,NaN,NaN,4.928571,NaN
19,AR Patel,18.200000,15.727273,0.461538,0.846154,-2.472727,0.384615

In [13]:
# ============================================
# COMBINE RECENT-FORM FEATURES
# ============================================

recent_form = latest_features.merge(
    recent_3_features,
    on="player",
    how="outer"
)

recent_form = recent_form.merge(
    first_last,
    on="player",
    how="outer"
)

recent_form = recent_form.merge(
    batting_consistency,
    on="player",
    how="outer"
)

recent_form = recent_form.merge(
    bowling_consistency,
    on="player",
    how="outer"
)

recent_form = recent_form.merge(
    efficiency_trend[
        [
            "player",
            "first_runs_per_match",
            "latest_runs_per_match",
            "first_wickets_per_match",
            "latest_wickets_per_match",
            "runs_per_match_trend",
            "wickets_per_match_trend"
        ]
    ],
    on="player",
    how="outer"
)

print("Shape:", recent_form.shape)
print("Players:", recent_form["player"].nunique())

display(recent_form.head(20))

Shape: (384, 44)
Players: 384

,player,latest_runs,latest_strike_rate,latest_fours,latest_sixes,latest_boundary_percentage,latest_wickets,latest_economy,latest_bowling_strike_rate,recent_3_seasons,...,runs_std,strike_rate_std,wickets_std,economy_std,first_runs_per_match,latest_runs_per_match,first_wickets_per_match,latest_wickets_per_match,runs_per_match_trend,wickets_per_match_trend
0,A Badoni,215.0,152.482270,23.0,9.0,67.906977,0.0,14.000000,NaN,3,...,60.661355,11.203217,1.095445,5.624322,14.636364,21.500000,1.000000,0.000000,6.863636,-1.000000
1,A Kamboj,58.0,161.111111,3.0,4.0,62.068966,21.0,10.529801,14.380952,3,...,29.484459,31.590226,9.712535,1.766217,2.000000,14.500000,0.666667,1.500000,12.500000,0.833333
2,A Manohar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,...,48.805737,40.379910,0.000000,NaN,15.428571,12.200000,NaN,NaN,-3.228571,NaN
3,A Mhatre,201.0,179.464286,20.0,12.0,75.621891,0.0,NaN,NaN,2,...,27.577164,6.726065,0.000000,NaN,34.285714,33.500000,NaN,NaN,-0.785714,NaN
4,A Mishra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,...,13.435029,NaN,4.242641,1.525862,19.000000,19.000000,1.000000,1.000000,0.000000,0.000000
5,A Nortje,0.0,0.000000,0.0,0.0,NaN,0.0,9.750000,NaN,3,...,16.071714,56.634716,4.615192,1.792162,1.000000,0.000000,1.500000,0.000000,-1.000000,-1.500000
6,A Raghuvanshi,422.0,147.038328,40.0,19.0,64.928910,0.0,NaN,NaN,3,...,129.572374,7.535649,0.000000,NaN,23.285714,35.166667,NaN,NaN,11.880952,NaN
7,A Tomar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,...,NaN,NaN,NaN,NaN,4.000000,4.000000,NaN,NaN,0.000000,NaN
8,A Zampa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,...,7.071068,NaN,4.242641,2.265956,3.333333,3.333333,1.333333,1.000000,0.000000,-0.333333
9,AA Kulkarni,17.0,68.000000,1.0,0.0,23.529412,0.0,NaN,NaN,2,...,5.656854,31.466252,0.000000,NaN,4.500000,8.500000,NaN,NaN,4.000000,NaN
10,AD Russell,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,...,70.301138,19.176003,6.130525,1.003451,27.916667,16.700000,1.307692,0.888889,-11.216667,-0.418803
11,AF Milne,2.0,100.000000,0.0,0.0,0.000000,0.0,12.300000,NaN,2,...,1.414214,NaN,0.000000,3.323402,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000
12,AJ Finch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,...,NaN,NaN,NaN,NaN,17.200000,17.200000,NaN,NaN,0.000000,NaN
13,AJ Hosein,5.0,166.666667,0.0,0.0,0.000000,8.0,8.027027,18.500000,2,...,7.778175,4.714045,4.949747,1.395103,16.000000,2.500000,1.000000,1.142857,-13.500000,0.142857
14,AJ Turner,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,...,NaN,NaN,NaN,NaN,10.500000,10.500000,NaN,NaN,0.000000,NaN
15,AJ Tye,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,0.666667,0.666667,NaN,0.000000
16,AK Markram,231.0,139.156627,20.0,11.0,63.203463,0.0,13.833333,NaN,3,...,101.643987,10.103424,1.643168,2.447130,31.750000,21.000000,0.250000,0.000000,-10.750000,-0.250000
17,AM Ghazanfar,2.0,66.666667,0.0,0.0,0.000000,15.0,10.017167,15.533333,1,...,NaN,NaN,NaN,NaN,2.000000,2.000000,1.363636,1.363636,0.000000,0.000000
18,AM Rahane,335.0,135.080645,25.0,18.0,62.089552,0.0,NaN,NaN,3,...,100.198303,25.764596,0.000000,NaN,19.000000,23.928571,NaN,NaN,4.928571,NaN
19,AR Patel,173.0,132.061069,16.0,6.0,57.803468,11.0,8.181818,24.000000,3,...,48.571597,11.684454,3.033150,0.600153,18.200000,15.727273,0.461538,0.846154,-2.472727,0.384615

In [14]:
print(
    "Duplicate players:",
    recent_form["player"].duplicated().sum()
)
print("Missing player names:", recent_form["player"].isna().sum())

Duplicate players: 0
Missing player names: 0

In [15]:
# ============================================
# RECENCY WEIGHTS
# ============================================

season_weights = {
    2022: 0.10,
    2023: 0.15,
    2024: 0.20,
    2025: 0.25,
    2026: 0.30
}

print("Weights:", season_weights)
print("Weight total:", sum(season_weights.values()))

Weights: {2022: 0.1, 2023: 0.15, 2024: 0.2, 2025: 0.25, 2026: 0.3}
Weight total: 1.0

In [16]:
# ============================================
# WEIGHTED RECENT PERFORMANCE
# ============================================

weighted_df = df.copy()

weighted_df["season_weight"] = (
    weighted_df["season"].map(season_weights)
)

weighted_df["weighted_runs"] = (
    weighted_df["runs"] *
    weighted_df["season_weight"]
)

weighted_df["weighted_wickets"] = (
    weighted_df["wickets"] *
    weighted_df["season_weight"]
)

weighted_performance = (
    weighted_df
    .groupby("player", as_index=False)
    .agg(
        weighted_runs=("weighted_runs", "sum"),
        weighted_wickets=("weighted_wickets", "sum")
    )
)

display(weighted_performance.head(20))

           player  weighted_runs  weighted_wickets
0        A Badoni         245.55              0.70
1        A Kamboj          21.30              8.70
2       A Manohar          44.95              0.00
3        A Mhatre         120.30              0.00
4        A Mishra           2.85              1.25
5        A Nortje           6.45              4.05
6   A Raghuvanshi         234.20              0.00
7         A Tomar           0.40              0.00
8         A Zampa           1.50              1.70
9     AA Kulkarni           6.90              0.00
10     AD Russell         153.70              8.55
11       AF Milne           0.60              0.00
12       AJ Finch           8.60              0.00
13      AJ Hosein           3.90              2.55
14      AJ Turner           4.20              0.00
15         AJ Tye           0.00              0.20
16     AK Markram         299.85              1.25
17   AM Ghazanfar           0.60              4.50
18      AM Rahane         308.60              0.00
19       AR Patel         225.30              9.00

In [17]:
weighted_df["weighted_balls"] = (
    weighted_df["batting_balls"] *
    weighted_df["season_weight"]
)

weighted_df["weighted_bowling_balls"] = (
    weighted_df["bowling_balls"] *
    weighted_df["season_weight"]
)

weighted_df["weighted_runs_conceded"] = (
    weighted_df["runs_conceded"] *
    weighted_df["season_weight"]
)

weighted_performance = (
    weighted_df
    .groupby("player", as_index=False)
    .agg(
        weighted_runs=("weighted_runs", "sum"),
        weighted_balls=("weighted_balls", "sum"),
        weighted_wickets=("weighted_wickets", "sum"),
        weighted_bowling_balls=("weighted_bowling_balls", "sum"),
        weighted_runs_conceded=("weighted_runs_conceded", "sum")
    )
)

weighted_performance["weighted_strike_rate"] = (
    weighted_performance["weighted_runs"] /
    weighted_performance["weighted_balls"].replace(0, np.nan)
) * 100

weighted_performance["weighted_economy"] = (
    weighted_performance["weighted_runs_conceded"] /
    (weighted_performance["weighted_bowling_balls"] / 6)
        .replace(0, np.nan)
)

display(weighted_performance.head(20))

,player,weighted_runs,weighted_balls,weighted_wickets,weighted_bowling_balls,weighted_runs_conceded,weighted_strike_rate,weighted_economy
0,A Badoni,245.55,170.40,0.70,8.05,13.55,144.102113,10.099379
1,A Kamboj,21.30,14.20,8.70,134.85,224.80,150.000000,10.002225
2,A Manohar,44.95,38.40,0.00,0.00,0.00,117.057292,NaN
3,A Mhatre,120.30,65.35,0.00,0.00,0.00,184.085692,NaN
4,A Mishra,2.85,4.50,1.25,19.50,26.35,63.333333,8.107692
5,A Nortje,6.45,6.85,4.05,93.50,167.55,94.160584,10.751872
6,A Raghuvanshi,234.20,160.60,0.00,0.00,0.00,145.828144,NaN
7,A Tomar,0.40,0.80,0.00,0.00,0.00,50.000000,NaN
8,A Zampa,1.50,2.40,1.70,31.80,51.70,62.500000,9.754717
9,AA Kulkarni,6.90,9.10,0.00,0.00,0.00,75.824176,NaN
10,AD Russell,153.70,90.85,8.55,93.00,166.85,169.179967,10.764516
11,AF Milne,0.60,0.60,0.00,7.50,14.20,100.000000,11.360000
12,AJ Finch,8.60,6.10,0.00,0.00,0.00,140.983607,NaN
13,AJ Hosein,3.90,2.40,2.55,48.00,65.40,162.500000,8.175000
14,AJ Turner,4.20,3.60,0.00,0.00,0.00,116.666667,NaN
15,AJ Tye,0.00,0.00,0.20,6.60,10.70,NaN,9.727273
16,AK Markram,299.85,216.15,1.25,40.65,70.30,138.723109,10.376384
17,AM Ghazanfar,0.60,0.90,4.50,69.90,116.70,66.666667,10.017167
18,AM Rahane,308.60,220.75,0.00,0.00,0.00,139.796149,NaN
19,AR Patel,225.30,159.00,9.00,254.10,336.45,141.698113,7.944510

In [18]:
recent_form = recent_form.merge(
    weighted_performance,
    on="player",
    how="left"
)

print("Final recent-form shape:", recent_form.shape)
display(recent_form.head(10))

Final recent-form shape: (384, 51)

,player,latest_runs,latest_strike_rate,latest_fours,latest_sixes,latest_boundary_percentage,latest_wickets,latest_economy,latest_bowling_strike_rate,recent_3_seasons,...,latest_wickets_per_match,runs_per_match_trend,wickets_per_match_trend,weighted_runs,weighted_balls,weighted_wickets,weighted_bowling_balls,weighted_runs_conceded,weighted_strike_rate,weighted_economy
0,A Badoni,215.0,152.482270,23.0,9.0,67.906977,0.0,14.000000,NaN,3,...,0.0,6.863636,-1.000000,245.55,170.40,0.70,8.05,13.55,144.102113,10.099379
1,A Kamboj,58.0,161.111111,3.0,4.0,62.068966,21.0,10.529801,14.380952,3,...,1.5,12.500000,0.833333,21.30,14.20,8.70,134.85,224.80,150.000000,10.002225
2,A Manohar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,...,NaN,-3.228571,NaN,44.95,38.40,0.00,0.00,0.00,117.057292,NaN
3,A Mhatre,201.0,179.464286,20.0,12.0,75.621891,0.0,NaN,NaN,2,...,NaN,-0.785714,NaN,120.30,65.35,0.00,0.00,0.00,184.085692,NaN
4,A Mishra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,...,1.0,0.000000,0.000000,2.85,4.50,1.25,19.50,26.35,63.333333,8.107692
5,A Nortje,0.0,0.000000,0.0,0.0,NaN,0.0,9.750000,NaN,3,...,0.0,-1.000000,-1.500000,6.45,6.85,4.05,93.50,167.55,94.160584,10.751872
6,A Raghuvanshi,422.0,147.038328,40.0,19.0,64.928910,0.0,NaN,NaN,3,...,NaN,11.880952,NaN,234.20,160.60,0.00,0.00,0.00,145.828144,NaN
7,A Tomar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,...,NaN,0.000000,NaN,0.40,0.80,0.00,0.00,0.00,50.000000,NaN
8,A Zampa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,...,1.0,0.000000,-0.333333,1.50,2.40,1.70,31.80,51.70,62.500000,9.754717
9,AA Kulkarni,17.0,68.000000,1.0,0.0,23.529412,0.0,NaN,NaN,2,...,NaN,4.000000,NaN,6.90,9.10,0.00,0.00,0.00,75.824176,NaN

In [19]:
recent_form = recent_form.merge(
    weighted_performance,
    on="player",
    how="left"
)

print("Final recent-form shape:", recent_form.shape)
display(recent_form.head(10))

Final recent-form shape: (384, 58)

,player,latest_runs,latest_strike_rate,latest_fours,latest_sixes,latest_boundary_percentage,latest_wickets,latest_economy,latest_bowling_strike_rate,recent_3_seasons,...,weighted_runs_conceded_x,weighted_strike_rate_x,weighted_economy_x,weighted_runs_y,weighted_balls_y,weighted_wickets_y,weighted_bowling_balls_y,weighted_runs_conceded_y,weighted_strike_rate_y,weighted_economy_y
0,A Badoni,215.0,152.482270,23.0,9.0,67.906977,0.0,14.000000,NaN,3,...,13.55,144.102113,10.099379,245.55,170.40,0.70,8.05,13.55,144.102113,10.099379
1,A Kamboj,58.0,161.111111,3.0,4.0,62.068966,21.0,10.529801,14.380952,3,...,224.80,150.000000,10.002225,21.30,14.20,8.70,134.85,224.80,150.000000,10.002225
2,A Manohar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,...,0.00,117.057292,NaN,44.95,38.40,0.00,0.00,0.00,117.057292,NaN
3,A Mhatre,201.0,179.464286,20.0,12.0,75.621891,0.0,NaN,NaN,2,...,0.00,184.085692,NaN,120.30,65.35,0.00,0.00,0.00,184.085692,NaN
4,A Mishra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,...,26.35,63.333333,8.107692,2.85,4.50,1.25,19.50,26.35,63.333333,8.107692
5,A Nortje,0.0,0.000000,0.0,0.0,NaN,0.0,9.750000,NaN,3,...,167.55,94.160584,10.751872,6.45,6.85,4.05,93.50,167.55,94.160584,10.751872
6,A Raghuvanshi,422.0,147.038328,40.0,19.0,64.928910,0.0,NaN,NaN,3,...,0.00,145.828144,NaN,234.20,160.60,0.00,0.00,0.00,145.828144,NaN
7,A Tomar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0.00,50.000000,NaN,0.40,0.80,0.00,0.00,0.00,50.000000,NaN
8,A Zampa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,...,51.70,62.500000,9.754717,1.50,2.40,1.70,31.80,51.70,62.500000,9.754717
9,AA Kulkarni,17.0,68.000000,1.0,0.0,23.529412,0.0,NaN,NaN,2,...,0.00,75.824176,NaN,6.90,9.10,0.00,0.00,0.00,75.824176,NaN

In [20]:
print("Players:", recent_form["player"].nunique())
print("Rows:", len(recent_form))

print(
    "Duplicate players:",
    recent_form["player"].duplicated().sum()
)

print("\nColumns:")
print(recent_form.columns.tolist())

Players: 384
Rows: 384
Duplicate players: 0

Columns:
['player', 'latest_runs', 'latest_strike_rate', 'latest_fours', 'latest_sixes', 'latest_boundary_percentage', 'latest_wickets', 'latest_economy', 'latest_bowling_strike_rate', 'recent_3_seasons', 'recent_3_runs', 'recent_3_balls', 'recent_3_fours', 'recent_3_sixes', 'recent_3_wickets', 'recent_3_bowling_balls', 'recent_3_runs_conceded', 'recent_3_strike_rate', 'recent_3_economy', 'recent_3_bowling_strike_rate', 'first_season', 'latest_season', 'first_runs', 'latest_runs_from_history', 'first_strike_rate', 'latest_strike_rate_from_history', 'first_wickets', 'latest_wickets_from_history', 'first_economy', 'latest_economy_from_history', 'runs_trend', 'strike_rate_trend', 'wickets_trend', 'economy_trend', 'runs_std', 'strike_rate_std', 'wickets_std', 'economy_std', 'first_runs_per_match', 'latest_runs_per_match', 'first_wickets_per_match', 'latest_wickets_per_match', 'runs_per_match_trend', 'wickets_per_match_trend', 'weighted_runs_x', 'weighted_balls_x', 'weighted_wickets_x', 'weighted_bowling_balls_x', 'weighted_runs_conceded_x', 'weighted_strike_rate_x', 'weighted_economy_x', 'weighted_runs_y', 'weighted_balls_y', 'weighted_wickets_y', 'weighted_bowling_balls_y', 'weighted_runs_conceded_y', 'weighted_strike_rate_y', 'weighted_economy_y']

In [21]:
output_path = r"C:\stuff\DATA MINING PROJECT\data\processed\ipl\recent_form_features.csv"

recent_form.to_csv(
    output_path,
    index=False
)

print("Saved successfully!")
print(output_path)

Saved successfully!
C:\stuff\DATA MINING PROJECT\data\processed\ipl\recent_form_features.csv